import type { Metadata } from "@/utils/meta";
import { fontVariables } from "@/lib/fonts";

import { Providers } from "@/components/providers"
import { Application } from "@/components/application"

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontVariables}>
        <Providers>
          <Application>
            {children}
          </Application>
        </Providers>
      </body>
    </html>
  );
}
