/* ============================================================
   EMOJI DATA — Unicode emoji, grouped by the standard Unicode
   categories (order preserved). Each entry is { name, char }
   where `name` is a stable lowercase shortcode.

   `emojiCategories` keeps the grouped/ordered structure (for
   pickers and the showcase); `emojis` is the flat name→char
   lookup the <Emoji> component reads.

   Names are unique across ALL categories so the flat lookup
   stays unambiguous. Extend any category by adding { name, char }
   entries with a fresh name.
   ============================================================ */

export const emojiCategories = {
  "Smileys & Emotion": [
    { name: "grinning", char: "😀" }, { name: "smiley", char: "😃" }, { name: "smile", char: "😄" },
    { name: "grin", char: "😁" }, { name: "laughing", char: "😆" }, { name: "sweat-smile", char: "😅" },
    { name: "rofl", char: "🤣" }, { name: "joy", char: "😂" }, { name: "slightly-smiling", char: "🙂" },
    { name: "upside-down", char: "🙃" }, { name: "melting", char: "🫠" }, { name: "wink", char: "😉" },
    { name: "blush", char: "😊" }, { name: "innocent", char: "😇" }, { name: "smiling-tear", char: "🥲" },
    { name: "heart-eyes", char: "😍" }, { name: "star-struck", char: "🤩" }, { name: "blowing-kiss", char: "😘" },
    { name: "kissing", char: "😗" }, { name: "kissing-smiling", char: "😙" }, { name: "kissing-closed", char: "😚" },
    { name: "smiling-hearts", char: "🥰" }, { name: "yum", char: "😋" }, { name: "tongue-out", char: "😛" },
    { name: "winking-tongue", char: "😜" }, { name: "zany", char: "🤪" }, { name: "squinting-tongue", char: "😝" },
    { name: "money-mouth", char: "🤑" }, { name: "hugging", char: "🤗" }, { name: "hand-over-mouth", char: "🤭" },
    { name: "shushing", char: "🤫" }, { name: "thinking", char: "🤔" }, { name: "saluting", char: "🫡" },
    { name: "zipper-mouth", char: "🤐" }, { name: "raised-eyebrow", char: "🤨" }, { name: "neutral", char: "😐" },
    { name: "expressionless", char: "😑" }, { name: "no-mouth", char: "😶" }, { name: "dotted-face", char: "🫥" },
    { name: "smirk", char: "😏" }, { name: "unamused", char: "😒" }, { name: "rolling-eyes", char: "🙄" },
    { name: "grimacing", char: "😬" }, { name: "lying", char: "🤥" }, { name: "relieved", char: "😌" },
    { name: "pensive", char: "😔" }, { name: "sleepy", char: "😪" }, { name: "drooling", char: "🤤" },
    { name: "sleeping", char: "😴" }, { name: "mask", char: "😷" }, { name: "thermometer-face", char: "🤒" },
    { name: "bandage-face", char: "🤕" }, { name: "nauseated", char: "🤢" }, { name: "vomiting", char: "🤮" },
    { name: "sneezing", char: "🤧" }, { name: "hot-face", char: "🥵" }, { name: "cold-face", char: "🥶" },
    { name: "woozy", char: "🥴" }, { name: "dizzy-face", char: "😵" }, { name: "spiral-eyes", char: "😵‍💫" },
    { name: "exploding-head", char: "🤯" }, { name: "cowboy", char: "🤠" }, { name: "partying", char: "🥳" },
    { name: "disguised", char: "🥸" }, { name: "sunglasses", char: "😎" }, { name: "nerd", char: "🤓" },
    { name: "monocle", char: "🧐" }, { name: "confused", char: "😕" }, { name: "worried", char: "😟" },
    { name: "slightly-frowning", char: "🙁" }, { name: "frowning", char: "😦" }, { name: "anguished", char: "😧" },
    { name: "fearful", char: "😨" }, { name: "anxious", char: "😰" }, { name: "sad-relieved", char: "😥" },
    { name: "cry", char: "😢" }, { name: "sob", char: "😭" }, { name: "scream", char: "😱" },
    { name: "confounded", char: "😖" }, { name: "persevere", char: "😣" }, { name: "disappointed", char: "😞" },
    { name: "sweat", char: "😓" }, { name: "weary", char: "😩" }, { name: "tired", char: "😫" },
    { name: "yawning", char: "🥱" }, { name: "triumph", char: "😤" }, { name: "rage", char: "😡" },
    { name: "angry", char: "😠" }, { name: "cursing", char: "🤬" }, { name: "smiling-devil", char: "😈" },
    { name: "angry-devil", char: "👿" }, { name: "skull", char: "💀" }, { name: "skull-crossbones", char: "☠️" },
    { name: "poop", char: "💩" }, { name: "clown", char: "🤡" }, { name: "ogre", char: "👹" },
    { name: "goblin", char: "👺" }, { name: "ghost", char: "👻" }, { name: "alien", char: "👽" },
    { name: "alien-monster", char: "👾" }, { name: "robot", char: "🤖" }, { name: "grinning-cat", char: "😺" },
    { name: "joy-cat", char: "😹" }, { name: "heart-eyes-cat", char: "😻" }, { name: "crying-cat", char: "😿" },
    { name: "pouting-cat", char: "😾" }, { name: "see-no-evil", char: "🙈" }, { name: "hear-no-evil", char: "🙉" },
    { name: "speak-no-evil", char: "🙊" }, { name: "kiss-mark", char: "💋" }, { name: "love-letter", char: "💌" },
    { name: "cupid", char: "💘" }, { name: "gift-heart", char: "💝" }, { name: "revolving-hearts", char: "💞" },
    { name: "two-hearts", char: "💕" }, { name: "heart-decoration", char: "💟" }, { name: "speech-balloon", char: "💬" },
    { name: "thought-balloon", char: "💭" }, { name: "zzz", char: "💤" },
  ],
  "People & Body": [
    { name: "wave", char: "👋" }, { name: "raised-back-hand", char: "🤚" }, { name: "raised-hand", char: "✋" },
    { name: "vulcan", char: "🖖" }, { name: "ok-hand", char: "👌" }, { name: "pinch", char: "🤏" },
    { name: "pinched-fingers", char: "🤌" }, { name: "victory", char: "✌️" }, { name: "crossed-fingers", char: "🤞" },
    { name: "hand-with-fingers-splayed", char: "🖐️" }, { name: "love-you-gesture", char: "🤟" }, { name: "call-me", char: "🤙" },
    { name: "point-left", char: "👈" }, { name: "point-right", char: "👉" }, { name: "point-up-2", char: "👆" },
    { name: "middle-finger", char: "🖕" }, { name: "point-down", char: "👇" }, { name: "point-up", char: "☝️" },
    { name: "index-pointing-viewer", char: "🫵" }, { name: "thumbs-up", char: "👍" }, { name: "thumbs-down", char: "👎" },
    { name: "fist", char: "✊" }, { name: "punch", char: "👊" }, { name: "left-fist", char: "🤛" },
    { name: "right-fist", char: "🤜" }, { name: "clap", char: "👏" }, { name: "raising-hands", char: "🙌" },
    { name: "heart-hands", char: "🫶" }, { name: "open-hands", char: "👐" }, { name: "palms-up", char: "🤲" },
    { name: "handshake", char: "🤝" }, { name: "pray", char: "🙏" }, { name: "writing-hand", char: "✍️" },
    { name: "nail-polish", char: "💅" }, { name: "selfie", char: "🤳" }, { name: "muscle", char: "💪" },
    { name: "mechanical-arm", char: "🦾" }, { name: "mechanical-leg", char: "🦿" }, { name: "leg", char: "🦵" },
    { name: "foot", char: "🦶" }, { name: "ear", char: "👂" }, { name: "hearing-aid", char: "🦻" },
    { name: "nose", char: "👃" }, { name: "brain", char: "🧠" }, { name: "anatomical-heart", char: "🫀" },
    { name: "lungs", char: "🫁" }, { name: "tooth", char: "🦷" }, { name: "bone", char: "🦴" },
    { name: "eyes", char: "👀" }, { name: "eye", char: "👁️" }, { name: "tongue", char: "👅" },
    { name: "mouth", char: "👄" }, { name: "baby", char: "👶" }, { name: "child", char: "🧒" },
    { name: "boy", char: "👦" }, { name: "girl", char: "👧" }, { name: "person", char: "🧑" },
    { name: "man", char: "👨" }, { name: "woman", char: "👩" }, { name: "older-person", char: "🧓" },
    { name: "old-man", char: "👴" }, { name: "old-woman", char: "👵" }, { name: "blond-person", char: "👱" },
    { name: "bearded-person", char: "🧔" }, { name: "person-red-hair", char: "🧑‍🦰" }, { name: "person-curly-hair", char: "🧑‍🦱" },
    { name: "frowning-person", char: "🙍" }, { name: "pouting-person", char: "🙎" }, { name: "gesturing-no", char: "🙅" },
    { name: "gesturing-ok", char: "🙆" }, { name: "tipping-hand", char: "💁" }, { name: "raising-hand", char: "🙋" },
    { name: "deaf-person", char: "🧏" }, { name: "bowing", char: "🙇" }, { name: "facepalm", char: "🤦" },
    { name: "shrug", char: "🤷" }, { name: "health-worker", char: "🧑‍⚕️" }, { name: "student", char: "🧑‍🎓" },
    { name: "teacher", char: "🧑‍🏫" }, { name: "judge", char: "🧑‍⚖️" }, { name: "farmer", char: "🧑‍🌾" },
    { name: "cook", char: "🧑‍🍳" }, { name: "mechanic", char: "🧑‍🔧" }, { name: "factory-worker", char: "🧑‍🏭" },
    { name: "office-worker", char: "🧑‍💼" }, { name: "scientist", char: "🧑‍🔬" }, { name: "technologist", char: "🧑‍💻" },
    { name: "singer", char: "🧑‍🎤" }, { name: "artist", char: "🧑‍🎨" }, { name: "pilot", char: "🧑‍✈️" },
    { name: "astronaut", char: "🧑‍🚀" }, { name: "firefighter", char: "🧑‍🚒" }, { name: "police", char: "👮" },
    { name: "detective", char: "🕵️" }, { name: "guard", char: "💂" }, { name: "ninja", char: "🥷" },
    { name: "worker", char: "👷" }, { name: "royalty", char: "🫅" }, { name: "prince", char: "🤴" },
    { name: "princess", char: "👸" }, { name: "person-turban", char: "👳" }, { name: "person-skullcap", char: "👲" },
    { name: "person-headscarf", char: "🧕" }, { name: "person-tuxedo", char: "🤵" }, { name: "person-veil", char: "👰" },
    { name: "pregnant-woman", char: "🤰" }, { name: "breast-feeding", char: "🤱" }, { name: "baby-angel", char: "👼" },
    { name: "santa", char: "🎅" }, { name: "mrs-claus", char: "🤶" }, { name: "superhero", char: "🦸" },
    { name: "supervillain", char: "🦹" }, { name: "mage", char: "🧙" }, { name: "fairy", char: "🧚" },
    { name: "vampire", char: "🧛" }, { name: "merperson", char: "🧜" }, { name: "elf", char: "🧝" },
    { name: "genie", char: "🧞" }, { name: "zombie", char: "🧟" }, { name: "massage", char: "💆" },
    { name: "haircut", char: "💇" }, { name: "walking", char: "🚶" }, { name: "standing", char: "🧍" },
    { name: "kneeling", char: "🧎" }, { name: "running", char: "🏃" }, { name: "dancer", char: "💃" },
    { name: "man-dancing", char: "🕺" }, { name: "people-bunny-ears", char: "👯" }, { name: "person-steamy-room", char: "🧖" },
    { name: "person-climbing", char: "🧗" }, { name: "couple", char: "👫" }, { name: "family", char: "👪" },
    { name: "footprints", char: "👣" },
  ],
  "Animals & Nature": [
    { name: "monkey-face", char: "🐵" }, { name: "monkey", char: "🐒" }, { name: "gorilla", char: "🦍" },
    { name: "orangutan", char: "🦧" }, { name: "dog-face", char: "🐶" }, { name: "dog", char: "🐕" },
    { name: "guide-dog", char: "🦮" }, { name: "poodle", char: "🐩" }, { name: "wolf", char: "🐺" },
    { name: "fox", char: "🦊" }, { name: "raccoon", char: "🦝" }, { name: "cat-face", char: "🐱" },
    { name: "cat", char: "🐈" }, { name: "black-cat", char: "🐈‍⬛" }, { name: "lion", char: "🦁" },
    { name: "tiger-face", char: "🐯" }, { name: "tiger", char: "🐅" }, { name: "leopard", char: "🐆" },
    { name: "horse-face", char: "🐴" }, { name: "horse", char: "🐎" }, { name: "unicorn", char: "🦄" },
    { name: "zebra", char: "🦓" }, { name: "deer", char: "🦌" }, { name: "bison", char: "🦬" },
    { name: "cow-face", char: "🐮" }, { name: "ox", char: "🐂" }, { name: "cow", char: "🐄" },
    { name: "pig-face", char: "🐷" }, { name: "pig", char: "🐖" }, { name: "boar", char: "🐗" },
    { name: "pig-nose", char: "🐽" }, { name: "ram", char: "🐏" }, { name: "ewe", char: "🐑" },
    { name: "goat", char: "🐐" }, { name: "camel", char: "🐪" }, { name: "two-hump-camel", char: "🐫" },
    { name: "llama", char: "🦙" }, { name: "giraffe", char: "🦒" }, { name: "elephant", char: "🐘" },
    { name: "mammoth", char: "🦣" }, { name: "rhinoceros", char: "🦏" }, { name: "hippopotamus", char: "🦛" },
    { name: "mouse", char: "🐭" }, { name: "rat", char: "🐀" }, { name: "hamster", char: "🐹" },
    { name: "rabbit-face", char: "🐰" }, { name: "rabbit", char: "🐇" }, { name: "chipmunk", char: "🐿️" },
    { name: "beaver", char: "🦫" }, { name: "hedgehog", char: "🦔" }, { name: "bat", char: "🦇" },
    { name: "bear", char: "🐻" }, { name: "polar-bear", char: "🐻‍❄️" }, { name: "koala", char: "🐨" },
    { name: "panda", char: "🐼" }, { name: "sloth", char: "🦥" }, { name: "otter", char: "🦦" },
    { name: "skunk", char: "🦨" }, { name: "kangaroo", char: "🦘" }, { name: "badger", char: "🦡" },
    { name: "paw-prints", char: "🐾" }, { name: "turkey", char: "🦃" }, { name: "chicken", char: "🐔" },
    { name: "rooster", char: "🐓" }, { name: "hatching-chick", char: "🐣" }, { name: "baby-chick", char: "🐤" },
    { name: "bird", char: "🐦" }, { name: "penguin", char: "🐧" }, { name: "dove", char: "🕊️" },
    { name: "eagle", char: "🦅" }, { name: "duck", char: "🦆" }, { name: "swan", char: "🦢" },
    { name: "owl", char: "🦉" }, { name: "dodo", char: "🦤" }, { name: "flamingo", char: "🦩" },
    { name: "peacock", char: "🦚" }, { name: "parrot", char: "🦜" }, { name: "frog", char: "🐸" },
    { name: "crocodile", char: "🐊" }, { name: "turtle", char: "🐢" }, { name: "lizard", char: "🦎" },
    { name: "snake", char: "🐍" }, { name: "dragon-face", char: "🐲" }, { name: "dragon", char: "🐉" },
    { name: "sauropod", char: "🦕" }, { name: "t-rex", char: "🦖" }, { name: "whale", char: "🐳" },
    { name: "spouting-whale", char: "🐋" }, { name: "dolphin", char: "🐬" }, { name: "seal", char: "🦭" },
    { name: "fish", char: "🐟" }, { name: "tropical-fish", char: "🐠" }, { name: "blowfish", char: "🐡" },
    { name: "shark", char: "🦈" }, { name: "octopus", char: "🐙" }, { name: "shell", char: "🐚" },
    { name: "coral", char: "🪸" }, { name: "snail", char: "🐌" }, { name: "butterfly", char: "🦋" },
    { name: "bug", char: "🐛" }, { name: "ant", char: "🐜" }, { name: "bee", char: "🐝" },
    { name: "beetle", char: "🪲" }, { name: "ladybug", char: "🐞" }, { name: "cricket", char: "🦗" },
    { name: "cockroach", char: "🪳" }, { name: "spider", char: "🕷️" }, { name: "spider-web", char: "🕸️" },
    { name: "scorpion", char: "🦂" }, { name: "mosquito", char: "🦟" }, { name: "fly", char: "🪰" },
    { name: "worm", char: "🪱" }, { name: "microbe", char: "🦠" }, { name: "bouquet", char: "💐" },
    { name: "cherry-blossom", char: "🌸" }, { name: "white-flower", char: "💮" }, { name: "rosette", char: "🏵️" },
    { name: "rose", char: "🌹" }, { name: "wilted-flower", char: "🥀" }, { name: "hibiscus", char: "🌺" },
    { name: "sunflower", char: "🌻" }, { name: "blossom", char: "🌼" }, { name: "tulip", char: "🌷" },
    { name: "seedling", char: "🌱" }, { name: "potted-plant", char: "🪴" }, { name: "evergreen", char: "🌲" },
    { name: "deciduous-tree", char: "🌳" }, { name: "palm-tree", char: "🌴" }, { name: "cactus", char: "🌵" },
    { name: "sheaf", char: "🌾" }, { name: "herb", char: "🌿" }, { name: "shamrock", char: "☘️" },
    { name: "four-leaf-clover", char: "🍀" }, { name: "maple-leaf", char: "🍁" }, { name: "fallen-leaf", char: "🍂" },
    { name: "leaves", char: "🍃" }, { name: "mushroom", char: "🍄" },
  ],
  "Food & Drink": [
    { name: "grapes", char: "🍇" }, { name: "melon", char: "🍈" }, { name: "watermelon", char: "🍉" },
    { name: "orange", char: "🍊" }, { name: "lemon", char: "🍋" }, { name: "banana", char: "🍌" },
    { name: "pineapple", char: "🍍" }, { name: "mango", char: "🥭" }, { name: "apple", char: "🍎" },
    { name: "green-apple", char: "🍏" }, { name: "pear", char: "🍐" }, { name: "peach", char: "🍑" },
    { name: "cherries", char: "🍒" }, { name: "strawberry", char: "🍓" }, { name: "blueberries", char: "🫐" },
    { name: "kiwi", char: "🥝" }, { name: "tomato", char: "🍅" }, { name: "olive", char: "🫒" },
    { name: "coconut", char: "🥥" }, { name: "avocado", char: "🥑" }, { name: "eggplant", char: "🍆" },
    { name: "potato", char: "🥔" }, { name: "carrot", char: "🥕" }, { name: "corn", char: "🌽" },
    { name: "hot-pepper", char: "🌶️" }, { name: "bell-pepper", char: "🫑" }, { name: "cucumber", char: "🥒" },
    { name: "leafy-green", char: "🥬" }, { name: "broccoli", char: "🥦" }, { name: "garlic", char: "🧄" },
    { name: "onion", char: "🧅" }, { name: "peanuts", char: "🥜" }, { name: "beans", char: "🫘" },
    { name: "chestnut", char: "🌰" }, { name: "bread", char: "🍞" }, { name: "croissant", char: "🥐" },
    { name: "baguette", char: "🥖" }, { name: "flatbread", char: "🫓" }, { name: "pretzel", char: "🥨" },
    { name: "bagel", char: "🥯" }, { name: "pancakes", char: "🥞" }, { name: "waffle", char: "🧇" },
    { name: "cheese", char: "🧀" }, { name: "meat-on-bone", char: "🍖" }, { name: "poultry-leg", char: "🍗" },
    { name: "cut-of-meat", char: "🥩" }, { name: "bacon", char: "🥓" }, { name: "hamburger", char: "🍔" },
    { name: "fries", char: "🍟" }, { name: "pizza", char: "🍕" }, { name: "hotdog", char: "🌭" },
    { name: "sandwich", char: "🥪" }, { name: "taco", char: "🌮" }, { name: "burrito", char: "🌯" },
    { name: "tamale", char: "🫔" }, { name: "stuffed-flatbread", char: "🥙" }, { name: "falafel", char: "🧆" },
    { name: "egg", char: "🥚" }, { name: "fried-egg", char: "🍳" }, { name: "shallow-pan", char: "🥘" },
    { name: "stew", char: "🍲" }, { name: "fondue", char: "🫕" }, { name: "bowl-with-spoon", char: "🥣" },
    { name: "green-salad", char: "🥗" }, { name: "popcorn", char: "🍿" }, { name: "butter", char: "🧈" },
    { name: "salt", char: "🧂" }, { name: "canned-food", char: "🥫" }, { name: "bento", char: "🍱" },
    { name: "rice-cracker", char: "🍘" }, { name: "rice-ball", char: "🍙" }, { name: "rice", char: "🍚" },
    { name: "curry-rice", char: "🍛" }, { name: "ramen", char: "🍜" }, { name: "spaghetti", char: "🍝" },
    { name: "roasted-sweet-potato", char: "🍠" }, { name: "oden", char: "🍢" }, { name: "sushi", char: "🍣" },
    { name: "fried-shrimp", char: "🍤" }, { name: "fish-cake", char: "🍥" }, { name: "moon-cake", char: "🥮" },
    { name: "dango", char: "🍡" }, { name: "dumpling", char: "🥟" }, { name: "fortune-cookie", char: "🥠" },
    { name: "takeout-box", char: "🥡" }, { name: "crab", char: "🦀" }, { name: "lobster", char: "🦞" },
    { name: "shrimp", char: "🦐" }, { name: "squid", char: "🦑" }, { name: "oyster", char: "🦪" },
    { name: "ice-cream", char: "🍦" }, { name: "shaved-ice", char: "🍧" }, { name: "ice-cream-bowl", char: "🍨" },
    { name: "doughnut", char: "🍩" }, { name: "cookie", char: "🍪" }, { name: "birthday-cake", char: "🎂" },
    { name: "cake", char: "🍰" }, { name: "cupcake", char: "🧁" }, { name: "pie", char: "🥧" },
    { name: "chocolate", char: "🍫" }, { name: "candy", char: "🍬" }, { name: "lollipop", char: "🍭" },
    { name: "custard", char: "🍮" }, { name: "honey", char: "🍯" }, { name: "baby-bottle", char: "🍼" },
    { name: "milk", char: "🥛" }, { name: "coffee", char: "☕" }, { name: "teapot", char: "🫖" },
    { name: "tea", char: "🍵" }, { name: "sake", char: "🍶" }, { name: "champagne", char: "🍾" },
    { name: "wine", char: "🍷" }, { name: "cocktail", char: "🍸" }, { name: "tropical-drink", char: "🍹" },
    { name: "beer", char: "🍺" }, { name: "beers", char: "🍻" }, { name: "clinking-glasses", char: "🥂" },
    { name: "tumbler", char: "🥃" }, { name: "pouring-liquid", char: "🫗" }, { name: "cup-straw", char: "🥤" },
    { name: "bubble-tea", char: "🧋" }, { name: "beverage-box", char: "🧃" }, { name: "mate", char: "🧉" },
    { name: "ice", char: "🧊" }, { name: "chopsticks", char: "🥢" }, { name: "fork-and-knife-plate", char: "🍽️" },
    { name: "fork-and-knife", char: "🍴" }, { name: "spoon", char: "🥄" },
  ],
  "Travel & Places": [
    { name: "globe-europe", char: "🌍" }, { name: "globe-americas", char: "🌎" }, { name: "globe-asia", char: "🌏" },
    { name: "globe-meridians", char: "🌐" }, { name: "world-map", char: "🗺️" }, { name: "compass", char: "🧭" },
    { name: "snowy-mountain", char: "🏔️" }, { name: "mountain", char: "⛰️" }, { name: "volcano", char: "🌋" },
    { name: "mount-fuji", char: "🗻" }, { name: "camping", char: "🏕️" }, { name: "beach", char: "🏖️" },
    { name: "desert", char: "🏜️" }, { name: "desert-island", char: "🏝️" }, { name: "national-park", char: "🏞️" },
    { name: "stadium", char: "🏟️" }, { name: "classical-building", char: "🏛️" }, { name: "building-construction", char: "🏗️" },
    { name: "houses", char: "🏘️" }, { name: "derelict-house", char: "🏚️" }, { name: "house", char: "🏠" },
    { name: "house-garden", char: "🏡" }, { name: "office", char: "🏢" }, { name: "post-office", char: "🏣" },
    { name: "european-post-office", char: "🏤" }, { name: "hospital", char: "🏥" }, { name: "bank", char: "🏦" },
    { name: "hotel", char: "🏨" }, { name: "love-hotel", char: "🏩" }, { name: "convenience-store", char: "🏪" },
    { name: "school", char: "🏫" }, { name: "department-store", char: "🏬" }, { name: "factory", char: "🏭" },
    { name: "japanese-castle", char: "🏯" }, { name: "castle", char: "🏰" }, { name: "wedding", char: "💒" },
    { name: "tokyo-tower", char: "🗼" }, { name: "statue-of-liberty", char: "🗽" }, { name: "church", char: "⛪" },
    { name: "mosque", char: "🕌" }, { name: "hindu-temple", char: "🛕" }, { name: "synagogue", char: "🕍" },
    { name: "kaaba", char: "🕋" }, { name: "fountain", char: "⛲" }, { name: "tent", char: "⛺" },
    { name: "foggy", char: "🌁" }, { name: "night-stars", char: "🌃" }, { name: "cityscape", char: "🏙️" },
    { name: "sunrise-mountains", char: "🌄" }, { name: "sunrise", char: "🌅" }, { name: "dusk", char: "🌆" },
    { name: "sunset", char: "🌇" }, { name: "bridge", char: "🌉" }, { name: "hot-springs", char: "♨️" },
    { name: "carousel-horse", char: "🎠" }, { name: "ferris-wheel", char: "🎡" }, { name: "roller-coaster", char: "🎢" },
    { name: "barber-pole", char: "💈" }, { name: "circus-tent", char: "🎪" }, { name: "locomotive", char: "🚂" },
    { name: "railway-car", char: "🚃" }, { name: "bullet-train", char: "🚄" }, { name: "high-speed-train", char: "🚅" },
    { name: "train", char: "🚆" }, { name: "metro", char: "🚇" }, { name: "light-rail", char: "🚈" },
    { name: "station", char: "🚉" }, { name: "tram", char: "🚊" }, { name: "monorail", char: "🚝" },
    { name: "mountain-railway", char: "🚞" }, { name: "tram-car", char: "🚋" }, { name: "bus", char: "🚌" },
    { name: "oncoming-bus", char: "🚍" }, { name: "trolleybus", char: "🚎" }, { name: "minibus", char: "🚐" },
    { name: "ambulance", char: "🚑" }, { name: "fire-engine", char: "🚒" }, { name: "police-car", char: "🚓" },
    { name: "oncoming-police-car", char: "🚔" }, { name: "taxi", char: "🚕" }, { name: "oncoming-taxi", char: "🚖" },
    { name: "car", char: "🚗" }, { name: "oncoming-car", char: "🚘" }, { name: "sport-car", char: "🏎️" },
    { name: "pickup-truck", char: "🛻" }, { name: "delivery-truck", char: "🚚" }, { name: "articulated-lorry", char: "🚛" },
    { name: "tractor", char: "🚜" }, { name: "racing-motorcycle", char: "🏍️" }, { name: "motor-scooter", char: "🛵" },
    { name: "manual-wheelchair", char: "🦽" }, { name: "motorized-wheelchair", char: "🦼" }, { name: "auto-rickshaw", char: "🛺" },
    { name: "bike", char: "🚲" }, { name: "kick-scooter", char: "🛴" }, { name: "skateboard", char: "🛹" },
    { name: "roller-skate", char: "🛼" }, { name: "bus-stop", char: "🚏" }, { name: "motorway", char: "🛣️" },
    { name: "railway-track", char: "🛤️" }, { name: "oil-drum", char: "🛢️" }, { name: "fuel", char: "⛽" },
    { name: "traffic-light-h", char: "🚥" }, { name: "traffic-light", char: "🚦" }, { name: "stop-sign", char: "🛑" },
    { name: "construction", char: "🚧" }, { name: "anchor", char: "⚓" }, { name: "sailboat", char: "⛵" },
    { name: "canoe", char: "🛶" }, { name: "speedboat", char: "🚤" }, { name: "passenger-ship", char: "🛳️" },
    { name: "ferry", char: "⛴️" }, { name: "motor-boat", char: "🛥️" }, { name: "ship", char: "🚢" },
    { name: "airplane", char: "✈️" }, { name: "small-airplane", char: "🛩️" }, { name: "departure", char: "🛫" },
    { name: "arrival", char: "🛬" }, { name: "parachute", char: "🪂" }, { name: "seat", char: "💺" },
    { name: "helicopter", char: "🚁" }, { name: "suspension-railway", char: "🚟" }, { name: "cable-car", char: "🚠" },
    { name: "aerial-tramway", char: "🚡" }, { name: "satellite", char: "🛰️" }, { name: "rocket", char: "🚀" },
    { name: "flying-saucer", char: "🛸" }, { name: "luggage", char: "🧳" }, { name: "hourglass-flowing", char: "⏳" },
    { name: "watch", char: "⌚" }, { name: "alarm-clock", char: "⏰" },
  ],
  "Activities": [
    { name: "jack-o-lantern", char: "🎃" }, { name: "christmas-tree", char: "🎄" }, { name: "fireworks", char: "🎆" },
    { name: "sparkler", char: "🎇" }, { name: "firecracker", char: "🧨" }, { name: "balloon", char: "🎈" },
    { name: "party-popper", char: "🎉" }, { name: "confetti-ball", char: "🎊" }, { name: "tanabata-tree", char: "🎋" },
    { name: "pine-decoration", char: "🎍" }, { name: "dolls", char: "🎎" }, { name: "carp-streamer", char: "🎏" },
    { name: "wind-chime", char: "🎐" }, { name: "moon-ceremony", char: "🎑" }, { name: "red-envelope", char: "🧧" },
    { name: "ribbon", char: "🎀" }, { name: "gift", char: "🎁" }, { name: "reminder-ribbon", char: "🎗️" },
    { name: "ticket", char: "🎫" }, { name: "admission-tickets", char: "🎟️" }, { name: "medal-military", char: "🎖️" },
    { name: "trophy", char: "🏆" }, { name: "medal", char: "🏅" }, { name: "gold-medal", char: "🥇" },
    { name: "silver-medal", char: "🥈" }, { name: "bronze-medal", char: "🥉" }, { name: "soccer", char: "⚽" },
    { name: "baseball", char: "⚾" }, { name: "softball", char: "🥎" }, { name: "basketball", char: "🏀" },
    { name: "volleyball", char: "🏐" }, { name: "football", char: "🏈" }, { name: "rugby", char: "🏉" },
    { name: "tennis", char: "🎾" }, { name: "flying-disc", char: "🥏" }, { name: "bowling", char: "🎳" },
    { name: "cricket-game", char: "🏏" }, { name: "field-hockey", char: "🏑" }, { name: "ice-hockey", char: "🏒" },
    { name: "lacrosse", char: "🥍" }, { name: "ping-pong", char: "🏓" }, { name: "badminton", char: "🏸" },
    { name: "boxing", char: "🥊" }, { name: "martial-arts", char: "🥋" }, { name: "goal", char: "🥅" },
    { name: "golf", char: "⛳" }, { name: "ice-skate", char: "⛸️" }, { name: "fishing", char: "🎣" },
    { name: "diving-mask", char: "🤿" }, { name: "running-shirt", char: "🎽" }, { name: "ski", char: "🎿" },
    { name: "sled", char: "🛷" }, { name: "curling-stone", char: "🥌" }, { name: "dart", char: "🎯" },
    { name: "yo-yo", char: "🪀" }, { name: "kite", char: "🪁" }, { name: "billiards", char: "🎱" },
    { name: "crystal-ball", char: "🔮" }, { name: "magic-wand", char: "🪄" }, { name: "video-game", char: "🎮" },
    { name: "joystick", char: "🕹️" }, { name: "slot-machine", char: "🎰" }, { name: "dice", char: "🎲" },
    { name: "puzzle", char: "🧩" }, { name: "teddy-bear", char: "🧸" }, { name: "pinata", char: "🪅" },
    { name: "nesting-dolls", char: "🪆" }, { name: "spade-suit", char: "♠️" }, { name: "heart-suit", char: "♥️" },
    { name: "diamond-suit", char: "♦️" }, { name: "club-suit", char: "♣️" }, { name: "chess-pawn", char: "♟️" },
    { name: "joker", char: "🃏" }, { name: "mahjong", char: "🀄" }, { name: "flower-cards", char: "🎴" },
    { name: "performing-arts", char: "🎭" }, { name: "framed-picture", char: "🖼️" }, { name: "art", char: "🎨" },
    { name: "thread", char: "🧵" }, { name: "sewing-needle", char: "🪡" }, { name: "yarn", char: "🧶" },
    { name: "knot", char: "🪢" }, { name: "musical-score", char: "🎼" }, { name: "musical-note", char: "🎵" },
    { name: "musical-notes", char: "🎶" }, { name: "microphone-emoji", char: "🎤" }, { name: "headphones", char: "🎧" },
    { name: "radio-emoji", char: "📻" }, { name: "saxophone", char: "🎷" }, { name: "accordion", char: "🪗" },
    { name: "guitar", char: "🎸" }, { name: "piano", char: "🎹" }, { name: "trumpet", char: "🎺" },
    { name: "violin", char: "🎻" }, { name: "banjo", char: "🪕" }, { name: "drum", char: "🥁" },
    { name: "long-drum", char: "🪘" }, { name: "clapper", char: "🎬" },
  ],
  "Objects": [
    { name: "glasses", char: "👓" }, { name: "sunglasses-object", char: "🕶️" }, { name: "goggles", char: "🥽" },
    { name: "lab-coat", char: "🥼" }, { name: "safety-vest", char: "🦺" }, { name: "necktie", char: "👔" },
    { name: "t-shirt", char: "👕" }, { name: "jeans", char: "👖" }, { name: "scarf", char: "🧣" },
    { name: "gloves", char: "🧤" }, { name: "coat", char: "🧥" }, { name: "socks", char: "🧦" },
    { name: "dress", char: "👗" }, { name: "kimono", char: "👘" }, { name: "sari", char: "🥻" },
    { name: "one-piece-swimsuit", char: "🩱" }, { name: "briefs", char: "🩲" }, { name: "shorts", char: "🩳" },
    { name: "bikini", char: "👙" }, { name: "womans-clothes", char: "👚" }, { name: "purse", char: "👛" },
    { name: "handbag", char: "👜" }, { name: "clutch-bag", char: "👝" }, { name: "shopping-bags", char: "🛍️" },
    { name: "backpack", char: "🎒" }, { name: "thong-sandal", char: "🩴" }, { name: "mans-shoe", char: "👞" },
    { name: "running-shoe", char: "👟" }, { name: "hiking-boot", char: "🥾" }, { name: "flat-shoe", char: "🥿" },
    { name: "high-heel", char: "👠" }, { name: "sandal", char: "👡" }, { name: "ballet-shoes", char: "🩰" },
    { name: "boot", char: "👢" }, { name: "crown", char: "👑" }, { name: "womans-hat", char: "👒" },
    { name: "top-hat", char: "🎩" }, { name: "graduation-cap", char: "🎓" }, { name: "billed-cap", char: "🧢" },
    { name: "military-helmet", char: "🪖" }, { name: "rescue-helmet", char: "⛑️" }, { name: "prayer-beads", char: "📿" },
    { name: "lipstick", char: "💄" }, { name: "ring", char: "💍" }, { name: "gem", char: "💎" },
    { name: "mute-object", char: "🔇" }, { name: "speaker-low", char: "🔈" }, { name: "speaker-medium", char: "🔉" },
    { name: "speaker", char: "🔊" }, { name: "loudspeaker", char: "📢" }, { name: "megaphone", char: "📣" },
    { name: "postal-horn", char: "📯" }, { name: "bell", char: "🔔" }, { name: "bell-slash", char: "🔕" },
    { name: "mobile-phone", char: "📱" }, { name: "phone-arrow", char: "📲" }, { name: "telephone", char: "☎️" },
    { name: "telephone-receiver", char: "📞" }, { name: "pager", char: "📟" }, { name: "fax", char: "📠" },
    { name: "battery", char: "🔋" }, { name: "low-battery", char: "🪫" }, { name: "plug", char: "🔌" },
    { name: "laptop", char: "💻" }, { name: "desktop", char: "🖥️" }, { name: "printer", char: "🖨️" },
    { name: "keyboard", char: "⌨️" }, { name: "mouse-device", char: "🖱️" }, { name: "trackball", char: "🖲️" },
    { name: "computer-disk", char: "💽" }, { name: "floppy-disk", char: "💾" }, { name: "optical-disk", char: "💿" },
    { name: "dvd", char: "📀" }, { name: "abacus", char: "🧮" }, { name: "movie-camera", char: "🎥" },
    { name: "film-frames", char: "🎞️" }, { name: "projector", char: "📽️" }, { name: "clapper-board", char: "🎬" },
    { name: "tv", char: "📺" }, { name: "camera", char: "📷" }, { name: "camera-flash", char: "📸" },
    { name: "video-camera", char: "📹" }, { name: "videocassette", char: "📼" }, { name: "magnifying-glass", char: "🔍" },
    { name: "magnifying-glass-right", char: "🔎" }, { name: "candle", char: "🕯️" }, { name: "bulb", char: "💡" },
    { name: "flashlight", char: "🔦" }, { name: "lantern", char: "🏮" }, { name: "diya-lamp", char: "🪔" },
    { name: "notebook-decorative", char: "📔" }, { name: "closed-book", char: "📕" }, { name: "open-book", char: "📖" },
    { name: "green-book", char: "📗" }, { name: "blue-book", char: "📘" }, { name: "orange-book", char: "📙" },
    { name: "books", char: "📚" }, { name: "notebook", char: "📓" }, { name: "ledger", char: "📒" },
    { name: "page-curl", char: "📃" }, { name: "scroll", char: "📜" }, { name: "page-facing-up", char: "📄" },
    { name: "newspaper", char: "📰" }, { name: "rolled-newspaper", char: "🗞️" }, { name: "bookmark-tabs", char: "📑" },
    { name: "bookmark", char: "🔖" }, { name: "label", char: "🏷️" }, { name: "money-bag", char: "💰" },
    { name: "coin", char: "🪙" }, { name: "dollar", char: "💵" }, { name: "yen-banknote", char: "💴" },
    { name: "euro-banknote", char: "💶" }, { name: "pound-banknote", char: "💷" }, { name: "money-wings", char: "💸" },
    { name: "credit-card", char: "💳" }, { name: "receipt", char: "🧾" }, { name: "chart-increasing-yen", char: "💹" },
    { name: "envelope", char: "✉️" }, { name: "email", char: "📧" }, { name: "incoming-envelope", char: "📨" },
    { name: "envelope-arrow", char: "📩" }, { name: "outbox-tray", char: "📤" }, { name: "inbox-tray", char: "📥" },
    { name: "package", char: "📦" }, { name: "mailbox-flag", char: "📫" }, { name: "mailbox", char: "📪" },
    { name: "open-mailbox-flag", char: "📬" }, { name: "open-mailbox", char: "📭" }, { name: "postbox", char: "📮" },
    { name: "ballot-box", char: "🗳️" }, { name: "pencil", char: "✏️" }, { name: "fountain-pen", char: "🖋️" },
    { name: "pen", char: "🖊️" }, { name: "paintbrush", char: "🖌️" }, { name: "crayon", char: "🖍️" },
    { name: "memo", char: "📝" }, { name: "briefcase", char: "💼" }, { name: "file-folder", char: "📁" },
    { name: "open-file-folder", char: "📂" }, { name: "card-index-dividers", char: "🗂️" }, { name: "calendar-emoji", char: "📅" },
    { name: "tear-off-calendar", char: "📆" }, { name: "spiral-notepad", char: "🗒️" }, { name: "spiral-calendar", char: "🗓️" },
    { name: "card-index", char: "📇" }, { name: "chart-increasing", char: "📈" }, { name: "chart-decreasing", char: "📉" },
    { name: "bar-chart", char: "📊" }, { name: "clipboard", char: "📋" }, { name: "pushpin", char: "📌" },
    { name: "round-pushpin", char: "📍" }, { name: "paperclip", char: "📎" }, { name: "linked-paperclips", char: "🖇️" },
    { name: "straight-ruler", char: "📏" }, { name: "triangular-ruler", char: "📐" }, { name: "scissors", char: "✂️" },
    { name: "card-file-box", char: "🗃️" }, { name: "file-cabinet", char: "🗄️" }, { name: "wastebasket", char: "🗑️" },
    { name: "lock", char: "🔒" }, { name: "unlock", char: "🔓" }, { name: "lock-pen", char: "🔏" },
    { name: "lock-key", char: "🔐" }, { name: "key", char: "🔑" }, { name: "old-key", char: "🗝️" },
    { name: "hammer", char: "🔨" }, { name: "axe", char: "🪓" }, { name: "pick", char: "⛏️" },
    { name: "hammer-and-pick", char: "⚒️" }, { name: "hammer-and-wrench", char: "🛠️" }, { name: "dagger", char: "🗡️" },
    { name: "crossed-swords", char: "⚔️" }, { name: "bomb", char: "💣" }, { name: "boomerang", char: "🪃" },
    { name: "bow-and-arrow", char: "🏹" }, { name: "shield", char: "🛡️" }, { name: "carpentry-saw", char: "🪚" },
    { name: "wrench", char: "🔧" }, { name: "screwdriver", char: "🪛" }, { name: "nut-and-bolt", char: "🔩" },
    { name: "gear", char: "⚙️" }, { name: "clamp", char: "🗜️" }, { name: "balance-scale", char: "⚖️" },
    { name: "white-cane", char: "🦯" }, { name: "link", char: "🔗" }, { name: "chains", char: "⛓️" },
    { name: "hook", char: "🪝" }, { name: "toolbox", char: "🧰" }, { name: "magnet", char: "🧲" },
    { name: "ladder", char: "🪜" }, { name: "test-tube", char: "🧪" }, { name: "petri-dish", char: "🧫" },
    { name: "dna", char: "🧬" }, { name: "microscope", char: "🔬" }, { name: "telescope", char: "🔭" },
    { name: "satellite-antenna", char: "📡" }, { name: "syringe", char: "💉" }, { name: "drop-of-blood", char: "🩸" },
    { name: "pill", char: "💊" }, { name: "bandage", char: "🩹" }, { name: "crutch", char: "🩼" },
    { name: "stethoscope-object", char: "🩺" }, { name: "x-ray", char: "🩻" }, { name: "door", char: "🚪" },
    { name: "elevator", char: "🛗" }, { name: "mirror", char: "🪞" }, { name: "window", char: "🪟" },
    { name: "bed", char: "🛏️" }, { name: "couch", char: "🛋️" }, { name: "chair", char: "🪑" },
    { name: "toilet", char: "🚽" }, { name: "plunger", char: "🪠" }, { name: "shower", char: "🚿" },
    { name: "bathtub", char: "🛁" }, { name: "mouse-trap", char: "🪤" }, { name: "razor", char: "🪒" },
    { name: "lotion", char: "🧴" }, { name: "safety-pin", char: "🧷" }, { name: "broom", char: "🧹" },
    { name: "basket", char: "🧺" }, { name: "toilet-paper", char: "🧻" }, { name: "bucket", char: "🪣" },
    { name: "soap", char: "🧼" }, { name: "bubbles", char: "🫧" }, { name: "toothbrush", char: "🪥" },
    { name: "sponge", char: "🧽" }, { name: "fire-extinguisher", char: "🧯" }, { name: "shopping-cart", char: "🛒" },
    { name: "cigarette", char: "🚬" }, { name: "coffin", char: "⚰️" }, { name: "headstone", char: "🪦" },
    { name: "funeral-urn", char: "⚱️" }, { name: "nazar-amulet", char: "🧿" }, { name: "hamsa", char: "🪬" },
    { name: "moai", char: "🗿" }, { name: "placard", char: "🪧" }, { name: "identification-card", char: "🪪" },
  ],
  "Symbols": [
    { name: "atm-sign", char: "🏧" }, { name: "litter-sign", char: "🚮" }, { name: "potable-water", char: "🚰" },
    { name: "wheelchair-symbol", char: "♿" }, { name: "mens-room", char: "🚹" }, { name: "womens-room", char: "🚺" },
    { name: "restroom", char: "🚻" }, { name: "baby-symbol", char: "🚼" }, { name: "water-closet", char: "🚾" },
    { name: "passport-control", char: "🛂" }, { name: "customs", char: "🛃" }, { name: "baggage-claim", char: "🛄" },
    { name: "left-luggage", char: "🛅" }, { name: "warning", char: "⚠️" }, { name: "children-crossing", char: "🚸" },
    { name: "no-entry", char: "⛔" }, { name: "prohibited", char: "🚫" }, { name: "no-bicycles", char: "🚳" },
    { name: "no-smoking", char: "🚭" }, { name: "no-littering", char: "🚯" }, { name: "non-potable-water", char: "🚱" },
    { name: "no-pedestrians", char: "🚷" }, { name: "no-phones", char: "📵" }, { name: "no-under-18", char: "🔞" },
    { name: "radioactive", char: "☢️" }, { name: "biohazard", char: "☣️" }, { name: "arrow-up", char: "⬆️" },
    { name: "arrow-up-right", char: "↗️" }, { name: "arrow-right", char: "➡️" }, { name: "arrow-down-right", char: "↘️" },
    { name: "arrow-down", char: "⬇️" }, { name: "arrow-down-left", char: "↙️" }, { name: "arrow-left", char: "⬅️" },
    { name: "arrow-up-left", char: "↖️" }, { name: "arrow-up-down", char: "↕️" }, { name: "arrow-left-right", char: "↔️" },
    { name: "arrow-back", char: "↩️" }, { name: "arrow-forward", char: "↪️" }, { name: "arrow-up-curve", char: "⤴️" },
    { name: "arrow-down-curve", char: "⤵️" }, { name: "clockwise-arrows", char: "🔃" }, { name: "counterclockwise-arrows", char: "🔄" },
    { name: "back-arrow", char: "🔙" }, { name: "end-arrow", char: "🔚" }, { name: "on-arrow", char: "🔛" },
    { name: "soon-arrow", char: "🔜" }, { name: "top-arrow", char: "🔝" }, { name: "place-of-worship", char: "🛐" },
    { name: "atom-symbol", char: "⚛️" }, { name: "om", char: "🕉️" }, { name: "star-of-david", char: "✡️" },
    { name: "wheel-of-dharma", char: "☸️" }, { name: "yin-yang", char: "☯️" }, { name: "latin-cross", char: "✝️" },
    { name: "orthodox-cross", char: "☦️" }, { name: "star-and-crescent", char: "☪️" }, { name: "peace-symbol", char: "☮️" },
    { name: "menorah", char: "🕎" }, { name: "dotted-six-pointed-star", char: "🔯" }, { name: "aries", char: "♈" },
    { name: "taurus", char: "♉" }, { name: "gemini", char: "♊" }, { name: "cancer", char: "♋" },
    { name: "leo", char: "♌" }, { name: "virgo", char: "♍" }, { name: "libra", char: "♎" },
    { name: "scorpio", char: "♏" }, { name: "sagittarius", char: "♐" }, { name: "capricorn", char: "♑" },
    { name: "aquarius", char: "♒" }, { name: "pisces", char: "♓" }, { name: "ophiuchus", char: "⛎" },
    { name: "shuffle", char: "🔀" }, { name: "repeat", char: "🔁" }, { name: "repeat-one", char: "🔂" },
    { name: "play-button", char: "▶️" }, { name: "fast-forward", char: "⏩" }, { name: "next-track", char: "⏭️" },
    { name: "play-pause", char: "⏯️" }, { name: "reverse-button", char: "◀️" }, { name: "rewind", char: "⏪" },
    { name: "previous-track", char: "⏮️" }, { name: "up-button", char: "🔼" }, { name: "fast-up", char: "⏫" },
    { name: "down-button", char: "🔽" }, { name: "fast-down", char: "⏬" }, { name: "pause-button", char: "⏸️" },
    { name: "stop-button", char: "⏹️" }, { name: "record-button", char: "⏺️" }, { name: "eject-button", char: "⏏️" },
    { name: "cinema", char: "🎦" }, { name: "dim-button", char: "🔅" }, { name: "bright-button", char: "🔆" },
    { name: "antenna-bars", char: "📶" }, { name: "vibration-mode", char: "📳" }, { name: "mobile-off", char: "📴" },
    { name: "female-sign", char: "♀️" }, { name: "male-sign", char: "♂️" }, { name: "transgender-symbol", char: "⚧️" },
    { name: "heavy-multiply", char: "✖️" }, { name: "heavy-plus", char: "➕" }, { name: "heavy-minus", char: "➖" },
    { name: "heavy-divide", char: "➗" }, { name: "heavy-equals", char: "🟰" }, { name: "infinity", char: "♾️" },
    { name: "double-exclamation", char: "‼️" }, { name: "exclamation-question", char: "⁉️" }, { name: "red-question", char: "❓" },
    { name: "white-question", char: "❔" }, { name: "white-exclamation", char: "❕" }, { name: "exclamation", char: "❗" },
    { name: "wavy-dash", char: "〰️" }, { name: "currency-exchange", char: "💱" }, { name: "heavy-dollar", char: "💲" },
    { name: "medical-symbol", char: "⚕️" }, { name: "recycle", char: "♻️" }, { name: "fleur-de-lis", char: "⚜️" },
    { name: "trident", char: "🔱" }, { name: "name-badge", char: "📛" }, { name: "japanese-beginner", char: "🔰" },
    { name: "hollow-red-circle", char: "⭕" }, { name: "check-mark-button", char: "✅" }, { name: "check-box", char: "☑️" },
    { name: "check-mark", char: "✔️" }, { name: "cross-mark", char: "❌" }, { name: "cross-mark-button", char: "❎" },
    { name: "curly-loop", char: "➰" }, { name: "double-curly-loop", char: "➿" }, { name: "part-alternation", char: "〽️" },
    { name: "eight-spoked-asterisk", char: "✳️" }, { name: "eight-pointed-star", char: "✴️" }, { name: "sparkle", char: "❇️" },
    { name: "copyright", char: "©️" }, { name: "registered", char: "®️" }, { name: "trade-mark", char: "™️" },
    { name: "keycap-hash", char: "#️⃣" }, { name: "keycap-asterisk", char: "*️⃣" }, { name: "keycap-0", char: "0️⃣" },
    { name: "keycap-1", char: "1️⃣" }, { name: "keycap-2", char: "2️⃣" }, { name: "keycap-3", char: "3️⃣" },
    { name: "keycap-10", char: "🔟" }, { name: "input-latin-uppercase", char: "🔠" }, { name: "input-latin-lowercase", char: "🔡" },
    { name: "input-numbers", char: "🔢" }, { name: "input-symbols", char: "🔣" }, { name: "input-latin", char: "🔤" },
    { name: "a-button", char: "🅰️" }, { name: "ab-button", char: "🆎" }, { name: "b-button", char: "🅱️" },
    { name: "cl-button", char: "🆑" }, { name: "cool-button", char: "🆒" }, { name: "free-button", char: "🆓" },
    { name: "information", char: "ℹ️" }, { name: "id-button", char: "🆔" }, { name: "circled-m", char: "Ⓜ️" },
    { name: "new-button", char: "🆕" }, { name: "ng-button", char: "🆖" }, { name: "o-button", char: "🅾️" },
    { name: "ok-button", char: "🆗" }, { name: "p-button", char: "🅿️" }, { name: "sos-button", char: "🆘" },
    { name: "up-button-symbol", char: "🆙" }, { name: "vs-button", char: "🆚" }, { name: "red-circle", char: "🔴" },
    { name: "orange-circle", char: "🟠" }, { name: "yellow-circle", char: "🟡" }, { name: "green-circle", char: "🟢" },
    { name: "blue-circle", char: "🔵" }, { name: "purple-circle", char: "🟣" }, { name: "brown-circle", char: "🟤" },
    { name: "black-circle", char: "⚫" }, { name: "white-circle", char: "⚪" }, { name: "red-square", char: "🟥" },
    { name: "orange-square", char: "🟧" }, { name: "yellow-square", char: "🟨" }, { name: "green-square", char: "🟩" },
    { name: "blue-square", char: "🟦" }, { name: "purple-square", char: "🟪" }, { name: "brown-square", char: "🟫" },
    { name: "black-square", char: "⬛" }, { name: "white-square", char: "⬜" }, { name: "orange-diamond", char: "🔶" },
    { name: "blue-diamond", char: "🔷" }, { name: "small-orange-diamond", char: "🔸" }, { name: "small-blue-diamond", char: "🔹" },
    { name: "red-triangle-up", char: "🔺" }, { name: "red-triangle-down", char: "🔻" }, { name: "diamond-with-dot", char: "💠" },
    { name: "radio-button", char: "🔘" }, { name: "white-square-button", char: "🔳" }, { name: "black-square-button", char: "🔲" },
  ],
  "Flags": [
    { name: "checkered-flag", char: "🏁" }, { name: "triangular-flag", char: "🚩" }, { name: "crossed-flags", char: "🎌" },
    { name: "black-flag", char: "🏴" }, { name: "white-flag", char: "🏳️" }, { name: "rainbow-flag", char: "🏳️‍🌈" },
    { name: "transgender-flag", char: "🏳️‍⚧️" }, { name: "pirate-flag", char: "🏴‍☠️" }, { name: "flag-un", char: "🇺🇳" },
    { name: "flag-us", char: "🇺🇸" }, { name: "flag-gb", char: "🇬🇧" }, { name: "flag-ca", char: "🇨🇦" },
    { name: "flag-mx", char: "🇲🇽" }, { name: "flag-br", char: "🇧🇷" }, { name: "flag-ar", char: "🇦🇷" },
    { name: "flag-cl", char: "🇨🇱" }, { name: "flag-co", char: "🇨🇴" }, { name: "flag-pe", char: "🇵🇪" },
    { name: "flag-ve", char: "🇻🇪" }, { name: "flag-uy", char: "🇺🇾" }, { name: "flag-fr", char: "🇫🇷" },
    { name: "flag-de", char: "🇩🇪" }, { name: "flag-es", char: "🇪🇸" }, { name: "flag-it", char: "🇮🇹" },
    { name: "flag-pt", char: "🇵🇹" }, { name: "flag-nl", char: "🇳🇱" }, { name: "flag-be", char: "🇧🇪" },
    { name: "flag-ch", char: "🇨🇭" }, { name: "flag-at", char: "🇦🇹" }, { name: "flag-ie", char: "🇮🇪" },
    { name: "flag-se", char: "🇸🇪" }, { name: "flag-no", char: "🇳🇴" }, { name: "flag-dk", char: "🇩🇰" },
    { name: "flag-fi", char: "🇫🇮" }, { name: "flag-pl", char: "🇵🇱" }, { name: "flag-gr", char: "🇬🇷" },
    { name: "flag-tr", char: "🇹🇷" }, { name: "flag-ru", char: "🇷🇺" }, { name: "flag-ua", char: "🇺🇦" },
    { name: "flag-jp", char: "🇯🇵" }, { name: "flag-kr", char: "🇰🇷" }, { name: "flag-cn", char: "🇨🇳" },
    { name: "flag-hk", char: "🇭🇰" }, { name: "flag-tw", char: "🇹🇼" }, { name: "flag-in", char: "🇮🇳" },
    { name: "flag-id", char: "🇮🇩" }, { name: "flag-th", char: "🇹🇭" }, { name: "flag-vn", char: "🇻🇳" },
    { name: "flag-ph", char: "🇵🇭" }, { name: "flag-my", char: "🇲🇾" }, { name: "flag-sg", char: "🇸🇬" },
    { name: "flag-sa", char: "🇸🇦" }, { name: "flag-ae", char: "🇦🇪" }, { name: "flag-il", char: "🇮🇱" },
    { name: "flag-eg", char: "🇪🇬" }, { name: "flag-za", char: "🇿🇦" }, { name: "flag-ng", char: "🇳🇬" },
    { name: "flag-ke", char: "🇰🇪" }, { name: "flag-au", char: "🇦🇺" }, { name: "flag-nz", char: "🇳🇿" },
    { name: "flag-eu", char: "🇪🇺" },
  ],
};

/* Flat name→char lookup, merged in category order. */
export const emojis = Object.fromEntries(
  Object.values(emojiCategories).flat().map((e) => [e.name, e.char])
);

/* Capitalized alias so the grouped data is reachable on the DS namespace
   (only capitalized exports are exposed on window.<Namespace>). */
export const EmojiCategories = emojiCategories;
