/* AUTOGENERATED — run: pnpm run gen:catalog */
import type { Category } from "./catalog.runtime";

export const CATEGORIES: Category[] = [
  {
    "name": "styles-text",
    "label": "Text",
    "type": "css-classes",
    "view": "text",
    "tags": [],
    "items": [
      {
        "title": "Rainbow Gradient",
        "slug": "gradient-rainbow",
        "cssClass": "text-gradient-rainbow",
        "sourceFile": "styles/classes/text/gradient-rainbow.css",
        "description": "Full spectrum rainbow gradient text",
        "category": "Colorful",
        "tags": [
          "gradient",
          "rainbow",
          "spectrum",
          "colorful"
        ],
        "previewText": "Rainbow",
        "background": "#1a1a1a",
        "usesData": false,
        "cssVariants": [],
        "bestFor": [
          "body",
          "heading",
          "display"
        ]
      },
      {
        "title": "text 3D",
        "slug": "text-3d",
        "cssClass": "text-3D",
        "sourceFile": "styles/classes/text/3d.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text 3D current",
        "slug": "text-3d-current",
        "cssClass": "text-3D-current",
        "sourceFile": "styles/classes/text/3d-current.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text 3D current dark",
        "slug": "text-3d-current-dark",
        "cssClass": "text-3D-current-dark",
        "sourceFile": "styles/classes/text/3d-current-dark.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text 3D faded hard",
        "slug": "text-3d-faded-hard",
        "cssClass": "text-3D-faded-hard",
        "sourceFile": "styles/classes/text/3d-faded-hard.css",
        "usesData": false,
        "cssVariants": [
          "bevel"
        ]
      },
      {
        "title": "text 3D faded medium",
        "slug": "text-3d-faded-medium",
        "cssClass": "text-3D-faded-medium",
        "sourceFile": "styles/classes/text/3d-faded-medium.css",
        "usesData": false,
        "cssVariants": [
          "less"
        ]
      },
      {
        "title": "text 3D faded soft",
        "slug": "text-3d-faded-soft",
        "cssClass": "text-3D-faded-soft",
        "sourceFile": "styles/classes/text/3d-faded-soft.css",
        "usesData": false,
        "cssVariants": [
          "less"
        ]
      },
      {
        "title": "text 3D glow",
        "slug": "text-3d-glow",
        "cssClass": "text-3D-glow",
        "sourceFile": "styles/classes/text/3d-glow.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text 3D glow clear",
        "slug": "text-3d-glow-clear",
        "cssClass": "text-3D-glow-clear",
        "sourceFile": "styles/classes/text/3d-glow-clear.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text 3D glow dark fill",
        "slug": "text-3d-glow-dark-fill",
        "cssClass": "text-3D-glow-dark-fill",
        "sourceFile": "styles/classes/text/3d-glow-dark-fill.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text 3D glow light fill",
        "slug": "text-3d-glow-light-fill",
        "cssClass": "text-3D-glow-light-fill",
        "sourceFile": "styles/classes/text/3d-glow-light-fill.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text 3D light",
        "slug": "text-3d-light",
        "cssClass": "text-3D-light",
        "sourceFile": "styles/classes/text/3d-light.css",
        "usesData": true,
        "cssVariants": [
          "bright",
          "brighter"
        ]
      },
      {
        "title": "text 3D plain",
        "slug": "text-3d-plain",
        "cssClass": "text-3D-plain",
        "sourceFile": "styles/classes/text/3d-plain.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text 3D sugar",
        "slug": "text-3d-sugar",
        "cssClass": "text-3D-sugar",
        "sourceFile": "styles/classes/text/3d-sugar.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text 3D sweet",
        "slug": "text-3d-sweet",
        "cssClass": "text-3D-sweet",
        "sourceFile": "styles/classes/text/3d-sweet.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text 3D thin",
        "slug": "text-3d-thin",
        "cssClass": "text-3D-thin",
        "sourceFile": "styles/classes/text/3d-thin.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text bevel",
        "slug": "text-bevel",
        "cssClass": "text-bevel",
        "sourceFile": "styles/classes/text/bevel.css",
        "usesData": true,
        "cssVariants": [
          "grlowing",
          "color",
          "bordered"
        ]
      },
      {
        "title": "text bevel",
        "slug": "text-bevel",
        "cssClass": "text-bevel",
        "sourceFile": "styles/classes/text/burn.css",
        "usesData": true,
        "cssVariants": [
          "color",
          "colored",
          "coloring",
          "dark"
        ]
      },
      {
        "title": "text bevel contrast",
        "slug": "text-bevel-contrast",
        "cssClass": "text-bevel-contrast",
        "sourceFile": "styles/classes/text/bevel-contrast.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text cut bright",
        "slug": "text-cut-bright",
        "cssClass": "text-cut-bright",
        "sourceFile": "styles/classes/text/cut-bright.css",
        "usesData": true,
        "cssVariants": [
          "inverse",
          "inverse2"
        ]
      },
      {
        "title": "text cut dark",
        "slug": "text-cut-dark",
        "cssClass": "text-cut-dark",
        "sourceFile": "styles/classes/text/cut-dark.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text distortion",
        "slug": "text-distortion",
        "cssClass": "text-distortion",
        "sourceFile": "styles/classes/text/distortion.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text double fill",
        "slug": "text-double-fill",
        "cssClass": "text-double-fill",
        "sourceFile": "styles/classes/text/double-fill.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text double stroke",
        "slug": "text-double-stroke",
        "cssClass": "text-double-stroke",
        "sourceFile": "styles/classes/text/double-stroke.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text element fire",
        "slug": "text-element-fire",
        "cssClass": "text-element-fire",
        "sourceFile": "styles/classes/text/element-fire.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text element ice",
        "slug": "text-element-ice",
        "cssClass": "text-element-ice",
        "sourceFile": "styles/classes/text/element-ice.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text emboss",
        "slug": "text-emboss",
        "cssClass": "text-emboss",
        "sourceFile": "styles/classes/text/emboss.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text emboss blend",
        "slug": "text-emboss-blend",
        "cssClass": "text-emboss-blend",
        "sourceFile": "styles/classes/text/emboss-blend.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text emboss bordered",
        "slug": "text-emboss-bordered",
        "cssClass": "text-emboss-bordered",
        "sourceFile": "styles/classes/text/emboss-bordered.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text emboss clear",
        "slug": "text-emboss-clear",
        "cssClass": "text-emboss-clear",
        "sourceFile": "styles/classes/text/emboss-clear.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text emboss plain",
        "slug": "text-emboss-plain",
        "cssClass": "text-emboss-plain",
        "sourceFile": "styles/classes/text/emboss-plain.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text emboss shadow",
        "slug": "text-emboss-shadow",
        "cssClass": "text-emboss-shadow",
        "sourceFile": "styles/classes/text/emboss-shadow.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text emboss stroke",
        "slug": "text-emboss-stroke",
        "cssClass": "text-emboss-stroke",
        "sourceFile": "styles/classes/text/emboss-stroke.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text fill alpha",
        "slug": "text-fill-alpha",
        "cssClass": "text-fill-alpha",
        "sourceFile": "styles/classes/text/fill-alpha.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text fill blend",
        "slug": "text-fill-blend",
        "cssClass": "text-fill-blend",
        "sourceFile": "styles/classes/text/fill-blend.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text fill crystal",
        "slug": "text-fill-crystal",
        "cssClass": "text-fill-crystal",
        "sourceFile": "styles/classes/text/fill-crystal.css",
        "usesData": false,
        "cssVariants": [
          "light"
        ]
      },
      {
        "title": "text fill glass",
        "slug": "text-fill-glass",
        "cssClass": "text-fill-glass",
        "sourceFile": "styles/classes/text/fill-glass.css",
        "usesData": false,
        "cssVariants": [
          "tinted",
          "lighter",
          "frosted",
          "frost",
          "clear"
        ]
      },
      {
        "title": "text fill glossy",
        "slug": "text-fill-glossy",
        "cssClass": "text-fill-glossy",
        "sourceFile": "styles/classes/text/fill-glossy.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text fill glow",
        "slug": "text-fill-glow",
        "cssClass": "text-fill-glow",
        "sourceFile": "styles/classes/text/fill-glow.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text fill solid",
        "slug": "text-fill-solid",
        "cssClass": "text-fill-solid",
        "sourceFile": "styles/classes/text/fill-solid.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text glass",
        "slug": "text-glass",
        "cssClass": "text-glass",
        "sourceFile": "styles/classes/text/glass.css",
        "usesData": true,
        "cssVariants": [
          "rushed"
        ]
      },
      {
        "title": "text glass new",
        "slug": "text-glass-new",
        "cssClass": "text-glass-new",
        "sourceFile": "styles/classes/text/glass-new.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text glass reflex",
        "slug": "text-glass-reflex",
        "cssClass": "text-glass-reflex",
        "sourceFile": "styles/classes/text/glass-reflex.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text glitch",
        "slug": "text-glitch",
        "cssClass": "text-glitch",
        "sourceFile": "styles/classes/text/glitch.css",
        "usesData": false,
        "cssVariants": [
          "darker",
          "lighter",
          "colored"
        ]
      },
      {
        "title": "text glitch giro",
        "slug": "text-glitch-giro",
        "cssClass": "text-glitch-giro",
        "sourceFile": "styles/classes/text/glitch-giro.css",
        "usesData": false,
        "cssVariants": [
          "darker",
          "lighter",
          "colored"
        ]
      },
      {
        "title": "text glitch layers",
        "slug": "text-glitch-layers",
        "cssClass": "text-glitch-layers",
        "sourceFile": "styles/classes/text/glitch-layers.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text glowing background",
        "slug": "text-glowing-background",
        "cssClass": "text-glowing-background",
        "sourceFile": "styles/classes/text/glowing-background.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text gold 3D",
        "slug": "text-gold-3d",
        "cssClass": "text-gold-3D",
        "sourceFile": "styles/classes/text/gold-3D.css",
        "usesData": true,
        "cssVariants": [
          "thin",
          "tick"
        ]
      },
      {
        "title": "text gold emboss",
        "slug": "text-gold-emboss",
        "cssClass": "text-gold-emboss",
        "sourceFile": "styles/classes/text/gold-emboss.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text gradient h",
        "slug": "text-gradient-h",
        "cssClass": "text-gradient-h",
        "sourceFile": "styles/classes/text/gradient-h.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text gradient motion",
        "slug": "text-gradient-motion",
        "cssClass": "text-gradient-motion",
        "sourceFile": "styles/classes/text/gradient-motion.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text gradient v",
        "slug": "text-gradient-v",
        "cssClass": "text-gradient-v",
        "sourceFile": "styles/classes/text/gradient-v.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text image",
        "slug": "text-image",
        "cssClass": "text-image",
        "sourceFile": "styles/classes/text/image.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text image light",
        "slug": "text-image-light",
        "cssClass": "text-image-light",
        "sourceFile": "styles/classes/text/image-light.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text image shadow",
        "slug": "text-image-shadow",
        "cssClass": "text-image-shadow",
        "sourceFile": "styles/classes/text/image-shadow.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text image stroke",
        "slug": "text-image-stroke",
        "cssClass": "text-image-stroke",
        "sourceFile": "styles/classes/text/image-stroke.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text inset",
        "slug": "text-inset",
        "cssClass": "text-inset",
        "sourceFile": "styles/classes/text/inset.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text inset blend",
        "slug": "text-inset-blend",
        "cssClass": "text-inset-blend",
        "sourceFile": "styles/classes/text/inset-blend.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text lighting",
        "slug": "text-lighting",
        "cssClass": "text-lighting",
        "sourceFile": "styles/classes/text/lighting copy.css",
        "usesData": true,
        "cssVariants": [
          "always"
        ]
      },
      {
        "title": "text lighting",
        "slug": "text-lighting",
        "cssClass": "text-lighting",
        "sourceFile": "styles/classes/text/lighting.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text lighting border",
        "slug": "text-lighting-border",
        "cssClass": "text-lighting-border",
        "sourceFile": "styles/classes/text/lighting-border.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text lighting bordered",
        "slug": "text-lighting-bordered",
        "cssClass": "text-lighting-bordered",
        "sourceFile": "styles/classes/text/lighting-bordered.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text lighting burned",
        "slug": "text-lighting-burned",
        "cssClass": "text-lighting-burned",
        "sourceFile": "styles/classes/text/lighting-burned.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text lighting focus",
        "slug": "text-lighting-focus",
        "cssClass": "text-lighting-focus",
        "sourceFile": "styles/classes/text/lighting-focus.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text lighting stroke",
        "slug": "text-lighting-stroke",
        "cssClass": "text-lighting-stroke",
        "sourceFile": "styles/classes/text/lighting-stroke.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text metallic chrome",
        "slug": "text-metallic-chrome",
        "cssClass": "text-metallic-chrome",
        "sourceFile": "styles/classes/text/metallic-chrome.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text neon border",
        "slug": "text-neon-border",
        "cssClass": "text-neon-border",
        "sourceFile": "styles/classes/text/neon-border.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text neon glow",
        "slug": "text-neon-glow",
        "cssClass": "text-neon-glow",
        "sourceFile": "styles/classes/text/neon-glow.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text pop art",
        "slug": "text-pop-art",
        "cssClass": "text-pop-art",
        "sourceFile": "styles/classes/text/pop-art.css",
        "usesData": false,
        "cssVariants": [
          "darker",
          "lighter"
        ]
      },
      {
        "title": "text retro wave",
        "slug": "text-retro-wave",
        "cssClass": "text-retro-wave",
        "sourceFile": "styles/classes/text/retro-wave.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text rgb split",
        "slug": "text-rgb-split",
        "cssClass": "text-rgb-split",
        "sourceFile": "styles/classes/text/rgb-split.css",
        "usesData": true,
        "cssVariants": [
          "blurred"
        ]
      },
      {
        "title": "text shadow 3D",
        "slug": "text-shadow-3d",
        "cssClass": "text-shadow-3D",
        "sourceFile": "styles/classes/text/shadow-3d.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text shadow animated",
        "slug": "text-shadow-animated",
        "cssClass": "text-shadow-animated",
        "sourceFile": "styles/classes/text/shadow-animated.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text shadow rainbow",
        "slug": "text-shadow-rainbow",
        "cssClass": "text-shadow-rainbow",
        "sourceFile": "styles/classes/text/shadow-rainbow.css",
        "usesData": false,
        "cssVariants": [
          "clear",
          "inverse",
          "multicolor"
        ]
      },
      {
        "title": "text shadow stripes",
        "slug": "text-shadow-stripes",
        "cssClass": "text-shadow-stripes",
        "sourceFile": "styles/classes/text/shadow-stripes.css",
        "usesData": true,
        "cssVariants": [
          "on"
        ]
      },
      {
        "title": "text striped layers",
        "slug": "text-striped-layers",
        "cssClass": "text-striped-layers",
        "sourceFile": "styles/classes/text/striped-layers.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text striped shaded",
        "slug": "text-striped-shaded",
        "cssClass": "text-striped-shaded",
        "sourceFile": "styles/classes/text/striped-shaded.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text striped staked",
        "slug": "text-striped-staked",
        "cssClass": "text-striped-staked",
        "sourceFile": "styles/classes/text/striped-staked.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text stripes",
        "slug": "text-stripes",
        "cssClass": "text-stripes",
        "sourceFile": "styles/classes/text/stripes.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text stripes colors",
        "slug": "text-stripes-colors",
        "cssClass": "text-stripes-colors",
        "sourceFile": "styles/classes/text/stripes-colors.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text stripes rainbow",
        "slug": "text-stripes-rainbow",
        "cssClass": "text-stripes-rainbow",
        "sourceFile": "styles/classes/text/stripes-rainbow.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text stroke fill",
        "slug": "text-stroke-fill",
        "cssClass": "text-stroke-fill",
        "sourceFile": "styles/classes/text/stroke-fill.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text stroke gradient",
        "slug": "text-stroke-gradient",
        "cssClass": "text-stroke-gradient",
        "sourceFile": "styles/classes/text/stroke-gradient.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text stroke image",
        "slug": "text-stroke-image",
        "cssClass": "text-stroke-image",
        "sourceFile": "styles/classes/text/stroke-image.css",
        "usesData": false,
        "cssVariants": [
          "with"
        ]
      },
      {
        "title": "text stroke inset",
        "slug": "text-stroke-inset",
        "cssClass": "text-stroke-inset",
        "sourceFile": "styles/classes/text/stroke-inset.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text stroke only",
        "slug": "text-stroke-only",
        "cssClass": "text-stroke-only",
        "sourceFile": "styles/classes/text/stroke-only.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text stroke shadow",
        "slug": "text-stroke-shadow",
        "cssClass": "text-stroke-shadow",
        "sourceFile": "styles/classes/text/stroke-shadow.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text stroke solid",
        "slug": "text-stroke-solid",
        "cssClass": "text-stroke-solid",
        "sourceFile": "styles/classes/text/stroke-solid.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "text texture dusted",
        "slug": "text-texture-dusted",
        "cssClass": "text-texture-dusted",
        "sourceFile": "styles/classes/text/texture-dusted.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture fluor",
        "slug": "text-texture-fluor",
        "cssClass": "text-texture-fluor",
        "sourceFile": "styles/classes/text/texture-fluor.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture glowing",
        "slug": "text-texture-glowing",
        "cssClass": "text-texture-glowing",
        "sourceFile": "styles/classes/text/texture-glowing.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture healtmap",
        "slug": "text-texture-healtmap",
        "cssClass": "text-texture-healtmap",
        "sourceFile": "styles/classes/text/texture-healtmap.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture neo",
        "slug": "text-texture-neo",
        "cssClass": "text-texture-neo",
        "sourceFile": "styles/classes/text/texture-neo.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture neoglow",
        "slug": "text-texture-neoglow",
        "cssClass": "text-texture-neoglow",
        "sourceFile": "styles/classes/text/texture-neoglow.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture neosplit",
        "slug": "text-texture-neosplit",
        "cssClass": "text-texture-neosplit",
        "sourceFile": "styles/classes/text/texture-neosplit.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture neostick",
        "slug": "text-texture-neostick",
        "cssClass": "text-texture-neostick",
        "sourceFile": "styles/classes/text/texture-neostick.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture neosticky",
        "slug": "text-texture-neosticky",
        "cssClass": "text-texture-neosticky",
        "sourceFile": "styles/classes/text/texture-neosticky.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture rushed",
        "slug": "text-texture-rushed",
        "cssClass": "text-texture-rushed",
        "sourceFile": "styles/classes/text/texture-rushed.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture rusted",
        "slug": "text-texture-rusted",
        "cssClass": "text-texture-rusted",
        "sourceFile": "styles/classes/text/texture-rusted.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "text texture toxic",
        "slug": "text-texture-toxic",
        "cssClass": "text-texture-toxic",
        "sourceFile": "styles/classes/text/texture-toxic.css",
        "usesData": true,
        "cssVariants": []
      },
      {
        "title": "wordart emboss",
        "slug": "wordart-emboss",
        "cssClass": "wordart-emboss",
        "sourceFile": "styles/classes/text/wordart-emboss.css",
        "usesData": false,
        "cssVariants": []
      }
    ]
  },
  {
    "name": "styles-links",
    "label": "Links",
    "type": "css-classes",
    "view": "text",
    "tags": [],
    "items": [
      {
        "title": "link fx",
        "slug": "link-fx",
        "cssClass": "link-fx",
        "sourceFile": "styles/classes/links/link-fx.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "link interactive",
        "slug": "link-interactive",
        "cssClass": "link-interactive",
        "sourceFile": "styles/classes/links/link-interactive.css",
        "usesData": false,
        "cssVariants": []
      }
    ]
  },
  {
    "name": "styles-highlights",
    "label": "Highlights",
    "type": "css-classes",
    "view": "text",
    "tags": [],
    "items": [
      {
        "title": "hl soft",
        "slug": "hl-soft",
        "cssClass": "hl-soft",
        "sourceFile": "styles/classes/highlights/highlights.css",
        "usesData": false,
        "cssVariants": []
      }
    ]
  },
  {
    "name": "styles-frames",
    "label": "Frames",
    "type": "css-classes",
    "view": "frames",
    "tags": [],
    "items": [
      {
        "title": "frame border gradient",
        "slug": "frame-border-gradient",
        "cssClass": "frame-border-gradient",
        "sourceFile": "styles/classes/frames/border-gradient.css",
        "usesData": false,
        "cssVariants": []
      },
      {
        "title": "frame border light",
        "slug": "frame-border-light",
        "cssClass": "frame-border-light",
        "sourceFile": "styles/classes/frames/border-light.css",
        "usesData": false,
        "cssVariants": []
      }
    ]
  },
  {
    "name": "presets-shapes",
    "label": "Shapes",
    "type": "variables",
    "view": "shape",
    "tags": [],
    "items": [
      {
        "title": "shape radius soft",
        "slug": "shape-radius-soft",
        "variableName": "--shape-radius-soft",
        "value": "clamp(8px, 2vw, 24px)",
        "sourceFile": "styles/presets/shapes.css"
      },
      {
        "title": "shape radius pill",
        "slug": "shape-radius-pill",
        "variableName": "--shape-radius-pill",
        "value": "9999px",
        "sourceFile": "styles/presets/shapes.css"
      },
      {
        "title": "shape radius squircle",
        "slug": "shape-radius-squircle",
        "variableName": "--shape-radius-squircle",
        "value": "clamp(24px, 6vw, 64px)",
        "sourceFile": "styles/presets/shapes.css"
      },
      {
        "title": "shape radius subtle",
        "slug": "shape-radius-subtle",
        "variableName": "--shape-radius-subtle",
        "value": "clamp(2px, 0.8vw, 10px)",
        "sourceFile": "styles/presets/shapes.css"
      },
      {
        "title": "shape clip diamond",
        "slug": "shape-clip-diamond",
        "variableName": "--shape-clip-diamond",
        "value": "polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)",
        "sourceFile": "styles/presets/shapes.css"
      },
      {
        "title": "shape clip hexagon",
        "slug": "shape-clip-hexagon",
        "variableName": "--shape-clip-hexagon",
        "value": "polygon(\n      25% 5%, 75% 5%,\n      100% 50%, 75% 95%,\n      25% 95%, 0% 50%\n    )",
        "sourceFile": "styles/presets/shapes.css"
      },
      {
        "title": "shape clip squircle",
        "slug": "shape-clip-squircle",
        "variableName": "--shape-clip-squircle",
        "value": "path('M10,0 Q16,0 20,4 Q24,8 24,14 Q24,20 20,24 Q16,28 10,28 Q4,28 0,24 Q-4,20 -4,14 Q-4,8 0,4 Q4,0 10,0Z')",
        "sourceFile": "styles/presets/shapes.css"
      },
      {
        "title": "shape radius circle",
        "slug": "shape-radius-circle",
        "variableName": "--shape-radius-circle",
        "value": "50%",
        "sourceFile": "styles/presets/shapes.css"
      }
    ]
  },
  {
    "name": "presets-borders",
    "label": "Borders",
    "type": "variables",
    "view": "shape",
    "tags": [],
    "items": []
  },
  {
    "name": "presets-shadows",
    "label": "Shadows",
    "type": "variables",
    "view": "shadow",
    "tags": [],
    "items": [
      {
        "title": "elevation card",
        "slug": "elevation-card",
        "variableName": "--elevation-card",
        "value": "0 1px 3px rgba(0, 0, 0, .08), 0 1px 2px rgba(0, 0, 0, .05)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow double",
        "slug": "shadow-double",
        "variableName": "--shadow-double",
        "value": ".05em .05em var(--style-fill-color),\n        .1em .1em var(--shadow-color)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow double large",
        "slug": "shadow-double-large",
        "variableName": "--shadow-double-large",
        "value": ".1em .1em var(--style-fill-color),\n        .2em .2em var(--shadow-color)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow rainbow",
        "slug": "shadow-rainbow",
        "variableName": "--shadow-rainbow",
        "value": "0.03em 0.03em #fc0049,\n        0.06em 0.06em #fe8f01,\n        0.09em 0.09em #fdf21f,\n        0.12em 0.12em #3fdf4b,\n        0.15em 0.15em #3462fe",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow multicolor",
        "slug": "shadow-multicolor",
        "variableName": "--shadow-multicolor",
        "value": "0.03em 0.03em 0em #eb452b,\n        0.06em 0.06em 0em #efa032,\n        0.09em 0.09em 0em #46b59b,\n        0.12em 0.12em 0em #017e7f,\n        0.15em 0.15em 0em #052939,\n        0.18em 0.18em 0em color-mix(in srgb, var(--foreground) 10%, var(--background) 100%),\n        0.21em 0.21em 0em color-mix(in srgb, var(--foreground) 10%, var(--background) 100%),\n        0.24em 0.24em 0em color-mix(in srgb, var(--foreground) 10%, var(--background) 100%),\n        0.27em 0.27em 0em color-mix(in srgb, var(--foreground) 10%, var(--background) 100%)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow long hard",
        "slug": "shadow-long-hard",
        "variableName": "--shadow-long-hard",
        "value": "0.01em 0.01em 0 #ef6209,\n        0.02em 0.02em 0 #ef6209,\n        0.03em 0.03em 0 #ef6209,\n        0.04em 0.04em 0 #ef6209,\n        0.05em 0.05em 0 #ef6209,\n        0.06em 0.06em 0 #ef6209,\n        0.07em 0.07em 0 #ef6209,\n        0.08em 0.08em 0 #ef6209,\n        0.09em 0.09em 0 #ef6209,\n        0.10em 0.10em 0 #ef6209,\n        0.11em 0.11em 0 #ef6209,\n        0.12em 0.12em 0 #ef6209,\n        0.13em 0.13em 0 #ef6209,\n        0.14em 0.14em 0 #ef6209,\n        0.15em 0.15em 0 #ef6209,\n        0.16em 0.16em 0 #ef6209,\n        0.17em 0.17em 0 #ef6209,\n        0.18em 0.18em 0 #ef6209,\n        0.19em 0.19em 0 #ef6209,\n        0.20em 0.20em 0 #ef6209,\n        0.21em 0.21em 0 #ef6209,\n        0.22em 0.22em 0 #ef6209",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow faded hard",
        "slug": "shadow-faded-hard",
        "variableName": "--shadow-faded-hard",
        "value": "0.01em 0.01em 0 rgb(0 0 0 / .80),\n        0.02em 0.02em 0 rgb(0 0 0 / .80),\n        0.03em 0.03em 0 rgb(0 0 0 / .80),\n        0.04em 0.04em 0 rgb(0 0 0 / .80),\n        0.05em 0.05em 0 rgb(0 0 0 / .70),\n        0.06em 0.06em 0 rgb(0 0 0 / .70),\n        0.07em 0.07em 0 rgb(0 0 0 / .70),\n        0.08em 0.08em 0 rgb(0 0 0 / .60),\n        0.09em 0.09em 0 rgb(0 0 0 / .60),\n        0.10em 0.10em 0 rgb(0 0 0 / .60),\n        0.11em 0.11em 0 rgb(0 0 0 / .55),\n        0.12em 0.12em 0 rgb(0 0 0 / .55),\n        0.13em 0.13em 0 rgb(0 0 0 / .50),\n        0.14em 0.14em 0 rgb(0 0 0 / .45),\n        0.15em 0.15em 0 rgb(0 0 0 / .40),\n        0.16em 0.16em 0 rgb(0 0 0 / .35),\n        0.17em 0.17em 0 rgb(0 0 0 / .30),\n        0.18em 0.18em 0 rgb(0 0 0 / .25),\n        0.19em 0.19em 0 rgb(0 0 0 / .20),\n        0.20em 0.20em 0 rgb(0 0 0 / .15),\n        0.21em 0.21em 0 rgb(0 0 0 / .10),\n        0.22em 0.22em 0 rgb(0 0 0 / .05)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow faded medium less 2",
        "slug": "shadow-faded-medium-less-2",
        "variableName": "--shadow-faded-medium-less-2",
        "value": "0.01em 0.01em 0.01em rgb(0 0 0 / .30),\n        0.02em 0.02em 0.01em rgb(0 0 0 / .30),\n        0.03em 0.03em 0.01em rgb(0 0 0 / .30),\n        0.04em 0.04em 0.01em rgb(0 0 0 / .30),\n        0.05em 0.05em 0.01em rgb(0 0 0 / .20),\n        0.06em 0.06em 0.01em rgb(0 0 0 / .20),\n        0.07em 0.07em 0.01em rgb(0 0 0 / .20),\n        0.08em 0.08em 0.01em rgb(0 0 0 / .20),\n        0.09em 0.09em 0.01em rgb(0 0 0 / .15),\n        0.10em 0.10em 0.01em rgb(0 0 0 / .15),\n        0.11em 0.11em 0.01em rgb(0 0 0 / .15),\n        0.12em 0.12em 0.01em rgb(0 0 0 / .15),\n        0.13em 0.13em 0.01em rgb(0 0 0 / .15),\n        0.14em 0.14em 0.01em rgb(0 0 0 / .10),\n        0.15em 0.15em 0.01em rgb(0 0 0 / .10),\n        0.16em 0.16em 0.01em rgb(0 0 0 / .10),\n        0.17em 0.17em 0.01em rgb(0 0 0 / .10),\n        0.18em 0.18em 0.01em rgb(0 0 0 / .05),\n        0.19em 0.19em 0.01em rgb(0 0 0 / .05),\n        0.20em 0.20em 0.01em rgb(0 0 0 / .05),\n        0.21em 0.21em 0.01em rgb(0 0 0 / .05),\n        0.22em 0.22em 0.01em rgb(0 0 0 / .05)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow faded medium less 1",
        "slug": "shadow-faded-medium-less-1",
        "variableName": "--shadow-faded-medium-less-1",
        "value": "0.01em 0.01em 0.01em rgb(0 0 0 / .25),\n        0.02em 0.02em 0.01em rgb(0 0 0 / .25),\n        0.03em 0.03em 0.01em rgb(0 0 0 / .25),\n        0.04em 0.04em 0.01em rgb(0 0 0 / .25),\n        0.05em 0.05em 0.01em rgb(0 0 0 / .15),\n        0.06em 0.06em 0.01em rgb(0 0 0 / .15),\n        0.07em 0.07em 0.01em rgb(0 0 0 / .15),\n        0.08em 0.08em 0.01em rgb(0 0 0 / .15),\n        0.09em 0.09em 0.01em rgb(0 0 0 / .10),\n        0.10em 0.10em 0.01em rgb(0 0 0 / .10),\n        0.11em 0.11em 0.01em rgb(0 0 0 / .10),\n        0.12em 0.12em 0.01em rgb(0 0 0 / .10),\n        0.13em 0.13em 0.01em rgb(0 0 0 / .10),\n        0.14em 0.14em 0.01em rgb(0 0 0 / .05),\n        0.15em 0.15em 0.01em rgb(0 0 0 / .05),\n        0.16em 0.16em 0.01em rgb(0 0 0 / .05),\n        0.17em 0.17em 0.01em rgb(0 0 0 / .05),\n        0.18em 0.18em 0.01em rgb(0 0 0 / .025),\n        0.19em 0.19em 0.01em rgb(0 0 0 / .025),\n        0.20em 0.20em 0.01em rgb(0 0 0 / .025),\n        0.21em 0.21em 0.01em rgb(0 0 0 / .025),\n        0.22em 0.22em 0.01em rgb(0 0 0 / .025)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow faded medium",
        "slug": "shadow-faded-medium",
        "variableName": "--shadow-faded-medium",
        "value": "0.01em 0.01em 0.01em rgb(0 0 0 / .16),\n        0.02em 0.02em 0.01em rgb(0 0 0 / .16),\n        0.03em 0.03em 0.01em rgb(0 0 0 / .16),\n        0.04em 0.04em 0.01em rgb(0 0 0 / .16),\n        0.05em 0.05em 0.01em rgb(0 0 0 / .12),\n        0.06em 0.06em 0.01em rgb(0 0 0 / .12),\n        0.07em 0.07em 0.01em rgb(0 0 0 / .12),\n        0.08em 0.08em 0.01em rgb(0 0 0 / .12),\n        0.09em 0.09em 0.01em rgb(0 0 0 / .06),\n        0.10em 0.10em 0.01em rgb(0 0 0 / .06),\n        0.11em 0.11em 0.01em rgb(0 0 0 / .06),\n        0.12em 0.12em 0.01em rgb(0 0 0 / .06),\n        0.13em 0.13em 0.01em rgb(0 0 0 / .06),\n        0.14em 0.14em 0.01em rgb(0 0 0 / .06),\n        0.15em 0.15em 0.01em rgb(0 0 0 / .06),\n        0.16em 0.16em 0.01em rgb(0 0 0 / .03),\n        0.17em 0.17em 0.01em rgb(0 0 0 / .03),\n        0.18em 0.18em 0.01em rgb(0 0 0 / .015),\n        0.19em 0.19em 0.01em rgb(0 0 0 / .015),\n        0.20em 0.20em 0.01em rgb(0 0 0 / .015),\n        0.21em 0.21em 0.01em rgb(0 0 0 / .015),\n        0.22em 0.22em 0.01em rgb(0 0 0 / .015)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow faded soft less 2",
        "slug": "shadow-faded-soft-less-2",
        "variableName": "--shadow-faded-soft-less-2",
        "value": "0.01em 0.01em 0.01em rgb(0 0 0 / .18),\n        0.02em 0.02em 0.01em rgb(0 0 0 / .18),\n        0.03em 0.03em 0.01em rgb(0 0 0 / .18),\n        0.04em 0.04em 0.01em rgb(0 0 0 / .18),\n        0.05em 0.05em 0.01em rgb(0 0 0 / .08),\n        0.06em 0.06em 0.01em rgb(0 0 0 / .08),\n        0.07em 0.07em 0.01em rgb(0 0 0 / .08),\n        0.08em 0.08em 0.01em rgb(0 0 0 / .08),\n        0.09em 0.09em 0.01em rgb(0 0 0 / .04),\n        0.10em 0.10em 0.01em rgb(0 0 0 / .04),\n        0.11em 0.11em 0.01em rgb(0 0 0 / .04),\n        0.12em 0.12em 0.01em rgb(0 0 0 / .04),\n        0.13em 0.13em 0.01em rgb(0 0 0 / .04),\n        0.14em 0.14em 0.01em rgb(0 0 0 / .04),\n        0.15em 0.15em 0.01em rgb(0 0 0 / .04),\n        0.16em 0.16em 0.01em rgb(0 0 0 / .02),\n        0.17em 0.17em 0.01em rgb(0 0 0 / .02),\n        0.18em 0.18em 0.01em rgb(0 0 0 / .01),\n        0.19em 0.19em 0.01em rgb(0 0 0 / .01),\n        0.20em 0.20em 0.01em rgb(0 0 0 / .01),\n        0.21em 0.21em 0.01em rgb(0 0 0 / .01),\n        0.22em 0.22em 0.01em rgb(0 0 0 / .01)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow faded soft less",
        "slug": "shadow-faded-soft-less",
        "variableName": "--shadow-faded-soft-less",
        "value": "0.01em 0.01em 0.01em rgb(0 0 0 / .10),\n        0.02em 0.02em 0.01em rgb(0 0 0 / .10),\n        0.03em 0.03em 0.01em rgb(0 0 0 / .10),\n        0.04em 0.04em 0.01em rgb(0 0 0 / .10),\n        0.05em 0.05em 0.01em rgb(0 0 0 / .05),\n        0.06em 0.06em 0.01em rgb(0 0 0 / .05),\n        0.07em 0.07em 0.01em rgb(0 0 0 / .05),\n        0.08em 0.08em 0.01em rgb(0 0 0 / .05),\n        0.09em 0.09em 0.01em rgb(0 0 0 / .03),\n        0.10em 0.10em 0.01em rgb(0 0 0 / .03),\n        0.11em 0.11em 0.01em rgb(0 0 0 / .03),\n        0.12em 0.12em 0.01em rgb(0 0 0 / .03),\n        0.13em 0.13em 0.01em rgb(0 0 0 / .03),\n        0.14em 0.14em 0.01em rgb(0 0 0 / .03),\n        0.15em 0.15em 0.01em rgb(0 0 0 / .03),\n        0.16em 0.16em 0.01em rgb(0 0 0 / .01),\n        0.17em 0.17em 0.01em rgb(0 0 0 / .01),\n        0.18em 0.18em 0.01em rgb(0 0 0 / .005),\n        0.19em 0.19em 0.01em rgb(0 0 0 / .005),\n        0.20em 0.20em 0.01em rgb(0 0 0 / .005),\n        0.21em 0.21em 0.01em rgb(0 0 0 / .005),\n        0.22em 0.22em 0.01em rgb(0 0 0 / .005)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow faded soft",
        "slug": "shadow-faded-soft",
        "variableName": "--shadow-faded-soft",
        "value": "0.01em 0.01em 0.01em rgba(0 0 0 / .08),\n        0.02em 0.02em 0.01em rgba(0 0 0 / .08),\n        0.03em 0.03em 0.01em rgba(0 0 0 / .08),\n        0.04em 0.04em 0.01em rgba(0 0 0 / .08),\n        0.05em 0.05em 0.01em rgba(0 0 0 / .08),\n        0.06em 0.06em 0.01em rgba(0 0 0 / .02),\n        0.07em 0.07em 0.01em rgba(0 0 0 / .02),\n        0.08em 0.08em 0.01em rgba(0 0 0 / .02),\n        0.09em 0.09em 0.01em rgba(0 0 0 / .02),\n        0.10em 0.10em 0.01em rgba(0 0 0 / .02),\n        0.11em 0.11em 0.01em rgba(0 0 0 / .02),\n        0.12em 0.12em 0.02em rgba(0 0 0 / .02),\n        0.13em 0.13em 0.02em rgba(0 0 0 / .02),\n        0.14em 0.14em 0.02em rgba(0 0 0 / .02),\n        0.15em 0.15em 0.02em rgba(0 0 0 / .01),\n        0.16em 0.16em 0.03em rgba(0 0 0 / .01),\n        0.17em 0.17em 0.03em rgba(0 0 0 / .01),\n        0.18em 0.18em 0.03em rgba(0 0 0 / .01),\n        0.19em 0.19em 0.03em rgba(0 0 0 / .01),\n        0.20em 0.20em 0.03em rgba(0 0 0 / .01),\n        0.21em 0.21em 0.03em rgba(0 0 0 / .01),\n        0.22em 0.22em 0.03em rgba(0 0 0 / .01)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "bevel top left",
        "slug": "bevel-top-left",
        "variableName": "--bevel-top-left",
        "value": "-0.01em -0.01em 0.02em rgb(255 255 255 / .36),\n        -0.01em -0.01em 0.02em rgb(255 255 255/ .36)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "bevel bottom right",
        "slug": "bevel-bottom-right",
        "variableName": "--bevel-bottom-right",
        "value": "0.01em 0.01em 0.005em rgb(255 255 255 / .1),\n        0.01em 0.01em 0.03em rgb(0 0 0 / .4),\n        0.02em 0.02em 0.05em rgb(255 255 255/ .2)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "bevel bottom bright",
        "slug": "bevel-bottom-bright",
        "variableName": "--bevel-bottom-bright",
        "value": "0em 0.01em 0.03em rgb(255 255 255 / 0.6)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "bevel bottom brighter",
        "slug": "bevel-bottom-brighter",
        "variableName": "--bevel-bottom-brighter",
        "value": "0em 0.01em 0.03em rgb(255 255 255 / 0.9)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "bevel sweet",
        "slug": "bevel-sweet",
        "variableName": "--bevel-sweet",
        "value": "2px 2px 1px #e94aa1,\n        -1px -1px 1px #c736f9,\n        -2px 2px 1px #e94aa1,\n        1px -1px 1px #f736f9",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "extrusion sweet",
        "slug": "extrusion-sweet",
        "variableName": "--extrusion-sweet",
        "value": "3px 1px 1px #4af7ff,\n        2px 2px 1px #165bfb,\n        4px 2px 1px #4af7ff,\n        3px 3px 1px #165bfb,\n        5px 3px 1px #4af7ff,\n        4px 4px 1px #165bfb,\n        6px 4px 1px #4af7ff,\n        5px 5px 1px #165bfb,\n        7px 5px 1px #4af7ff,\n        6px 6px 1px #165bfb,\n        8px 6px 1px #4af7ff,\n        7px 7px 1px #165bfb,\n        9px 7px 1px #4af7ff",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "extrusion thin",
        "slug": "extrusion-thin",
        "variableName": "--extrusion-thin",
        "value": "0 0.005em 0 #ccc,\n        0 0.010em 0 #c9c9c9,\n        0 0.015em 0 #bbb,\n        0 0.020em 0 #b9b9b9,\n        0 0.025em 0 #aaa",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "extrusion medium",
        "slug": "extrusion-medium",
        "variableName": "--extrusion-medium",
        "value": "0em 0.03em 0.04em rgba(16, 16, 16, 0.15),\n        0em 0.01em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 0%),\n        0em 0.02em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 1%),\n        0em 0.03em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 1%),\n        0em 0.04em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 2%),\n        0em 0.05em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 3%),\n        0em 0.06em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 5%),\n        0em 0.07em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 8%),\n        0em 0.08em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 13%),\n        0em 0.09em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 21%),\n        0em 0.10em 0.01em color-mix(in srgb, #b4b4b4 100%, #000 34%)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "extrusion current",
        "slug": "extrusion-current",
        "variableName": "--extrusion-current",
        "value": "0em 0.01em 0.02em rgb(0 0 0 / 0.1),\n        0em 0.01em 0.01em color-mix(in srgb, currentColor 100%, #000 10%),\n        0em 0.02em 0.01em color-mix(in srgb, currentColor 100%, #000 20%),\n        0em 0.03em 0.01em color-mix(in srgb, currentColor 100%, #000 20%),\n        0em 0.04em 0.01em color-mix(in srgb, currentColor 100%, #000 20%),\n        0em 0.05em 0.01em color-mix(in srgb, currentColor 100%, #000 20%),\n        0em 0.06em 0.01em color-mix(in srgb, currentColor 100%, #000 25%),\n        0em 0.07em 0.01em color-mix(in srgb, currentColor 100%, #000 30%),\n        0em 0.08em 0.01em color-mix(in srgb, currentColor 100%, #000 40%),\n        0em 0.09em 0.01em color-mix(in srgb, currentColor 100%, #000 50%),\n        0em 0.10em 0.01em color-mix(in srgb, currentColor 100%, #000 60%)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "extrusion current on dark",
        "slug": "extrusion-current-on-dark",
        "variableName": "--extrusion-current-on-dark",
        "value": "0em 0.01em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 10%),\n        0em 0.02em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 10%),\n        0em 0.03em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 20%),\n        0em 0.04em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 30%),\n        0em 0.05em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 40%),\n        0em 0.06em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 50%),\n        0em 0.07em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 60%),\n        0em 0.08em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 70%),\n        0em 0.09em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 80%),\n        0em 0.10em 0.01em color-mix(in srgb, currentColor 100%, var(--background) 90%)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "extrusion light",
        "slug": "extrusion-light",
        "variableName": "--extrusion-light",
        "value": "0 0 .01em,\n        0 0 .01em rgb(0 0 0 / .4),\n        0 .01em .01em rgb(0 0 0 / .4),\n        .01em 0 .01em,\n        .01em .01em .01em rgb(0 0 0 / .4),\n        .02em 0 .01em,\n        .02em .01em .01em rgb(0 0 0 / .4),\n        .03em 0 .01em,\n        .03em .01em .01em rgb(0 0 0 / .4),\n        .04em 0 .01em,\n        .04em .01em .01em rgb(0 0 0 / .4),\n        .05em 0 .01em,\n        .05em .01em .01em rgb(0 0 0 / .4),\n        .06em 0 .01em,\n        .06em .01em .01em rgb(0 0 0 / .4),\n        .07em 0 .01em,\n        .07em .01em .01em rgb(0 0 0 / .4),\n        .08em 0 .01em,\n        .08em .01em .01em rgb(0 0 0 / .4),\n        .09em 0 .01em,\n        .09em .01em .01em rgb(0 0 0 / .4),\n        .1em 0 .01em,\n        .1em .01em .01em rgb(0 0 0 / .4),\n\n        .01em 0 .01em rgb(0 0 0 / .4),\n        .02em 0 .01em rgb(0 0 0 / .4),\n        .03em 0 .01em rgb(0 0 0 / .4),\n        .04em 0 .01em rgb(0 0 0 / .4),\n        .05em 0 .01em rgb(0 0 0 / .4),\n        .06em 0 .01em rgb(0 0 0 / .4),\n        .07em 0 .01em rgb(0 0 0 / .4),\n        .08em 0 .01em rgb(0 0 0 / .4),\n        .09em 0 .01em rgb(0 0 0 / .4),\n        .1em 0 .01em rgb(0 0 0)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "extrusion right bottom",
        "slug": "extrusion-right-bottom",
        "variableName": "--extrusion-right-bottom",
        "value": "0em 0em 0.01em currentColor,\n        0em 0.01em 0.01em currentColor,\n        0em 0.02em 0.01em currentColor,\n\n        0.01em 0.01em 0.01em currentColor,\n        0.01em 0.02em 0.01em currentColor,\n        0.01em 0.03em 0.01em currentColor,\n\n        0.02em 0.02em 0.01em currentColor,\n        0.02em 0.03em 0.01em currentColor,\n        0.02em 0.04em 0.01em currentColor",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow base glow",
        "slug": "shadow-base-glow",
        "variableName": "--shadow-base-glow",
        "value": "0.01em 0.1em 0.2em rgb(0 0 0 / 0.2),\n        0.01em 0.1em 0.5em rgb(0 0 0 / 0.2),\n        \n        0.02em 0.04em 0.05em rgb(0 0 0 / 0.3),\n        0.00em 0.04em 0.05em rgb(0 0 0 / 0.3),\n        \n        0.04em 0.04em 0.05em rgb(0 0 0 / 0.3),\n        \n        \n        0.01em 0.01em 0.12em rgba(255, 255, 255, 0.5)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow ambient",
        "slug": "shadow-ambient",
        "variableName": "--shadow-ambient",
        "value": "0.01em 0.12em 0.02em rgb(0 0 0 / 0.4),\n        0.01em 0.16em 0.04em rgb(0 0 0 / 0.2),\n        0.01em 0.22em 0.15em rgb(0 0 0 / 0.2),\n        0.01em 0.26em 0.25em rgb(0 0 0 / 0.4)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow ambient small",
        "slug": "shadow-ambient-small",
        "variableName": "--shadow-ambient-small",
        "value": "0.01em 0.12em 0.02em rgb(0 0 0 / 0.2),\n        0.01em 0.16em 0.04em rgb(0 0 0 / 0.1),\n        0.01em 0.22em 0.15em rgb(0 0 0 / 0.1)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow medium",
        "slug": "shadow-medium",
        "variableName": "--shadow-medium",
        "value": "0 0.025em 0.005em rgba(0, 0, 0, .1),\n        0 0 0.025em rgba(0, 0, 0, .1),\n        0 0.005em 0.015em rgba(0, 0, 0, .3),\n        0 0.015em 0.025em rgba(0, 0, 0, .2),\n        0 0.025em 0.050em rgba(0, 0, 0, .2),\n        0 0.050em 0.050em rgba(0, 0, 0, .2),\n        0 0.100em 0.100em rgba(0, 0, 0, .15)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow top right",
        "slug": "shadow-top-right",
        "variableName": "--shadow-top-right",
        "value": "0.04em -0.04em 0.05em var(--shadow-color)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow bottom",
        "slug": "shadow-bottom",
        "variableName": "--shadow-bottom",
        "value": "0 0.03em 0.025em var(--shadow-color)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow simple",
        "slug": "shadow-simple",
        "variableName": "--shadow-simple",
        "value": "0em 0.021em 0.012em var(--shadow-color)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow dark",
        "slug": "shadow-dark",
        "variableName": "--shadow-dark",
        "value": "0em 0.01em 0.02em rgb(0 0 0 / 0.2)",
        "sourceFile": "styles/presets/shadows.css"
      },
      {
        "title": "shadow darker",
        "slug": "shadow-darker",
        "variableName": "--shadow-darker",
        "value": "0em 0.01em 0.02em rgb(0 0 0 / 0.4)",
        "sourceFile": "styles/presets/shadows.css"
      }
    ]
  },
  {
    "name": "presets-gradients",
    "label": "Gradients",
    "type": "variables",
    "view": "gradient",
    "tags": [],
    "items": [
      {
        "title": "gradient demo",
        "slug": "gradient-demo",
        "variableName": "--gradient-demo",
        "value": "linear-gradient(135deg, oklch(0.9 0.12 260), oklch(0.7 0.16 300))",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient to right",
        "slug": "gradient-to-right",
        "variableName": "--gradient-to-right",
        "value": "linear-gradient(to right, #84ff3d, #2eabff)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient to bottom",
        "slug": "gradient-to-bottom",
        "variableName": "--gradient-to-bottom",
        "value": "linear-gradient(#fee140, #fa709a)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient solid",
        "slug": "gradient-solid",
        "variableName": "--gradient-solid",
        "value": "linear-gradient(#09f1b8, #09f1b8)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient sweet",
        "slug": "gradient-sweet",
        "variableName": "--gradient-sweet",
        "value": "linear-gradient(142deg, #3fa1fb 0%, #fc46a8 100%)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient animated",
        "slug": "gradient-animated",
        "variableName": "--gradient-animated",
        "value": "linear-gradient(-45deg, #09f1b8, #00a2ff, #ff00d2, #54B2C7)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient multicolor",
        "slug": "gradient-multicolor",
        "variableName": "--gradient-multicolor",
        "value": "linear-gradient(to right, #09f1b8, #00a2ff, #ff00d2, #fed90f)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient glass stroke",
        "slug": "gradient-glass-stroke",
        "variableName": "--gradient-glass-stroke",
        "value": "linear-gradient(0deg,\n      transparent 5%,\n      rgba(255, 255, 255, .4))",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient glass fill",
        "slug": "gradient-glass-fill",
        "variableName": "--gradient-glass-fill",
        "value": "linear-gradient(0deg,\n      rgba(255, 255, 255, .1) 25%,\n      rgba(255, 255, 255, .0) 30%,\n      rgba(255, 255, 255, .0) 30%,\n      rgba(255, 255, 255, .4) 70%,\n      rgba(255, 255, 255, .6))",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient gold light",
        "slug": "gradient-gold-light",
        "variableName": "--gradient-gold-light",
        "value": "repeating-linear-gradient(5deg, var(--gold) 0%, var(--light-shadow) 23%, var(--gold) 31%)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient gold dark",
        "slug": "gradient-gold-dark",
        "variableName": "--gradient-gold-dark",
        "value": "repeating-linear-gradient(105deg, var(--gold) 0%, var(--dark-shadow) 5%, var(--gold) 12%)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient rainbow",
        "slug": "gradient-rainbow",
        "variableName": "--gradient-rainbow",
        "value": "linear-gradient(#fd004c 16.7%,\n      #fe9000 16.7%,\n      #fe9000 33.4%,\n      #fff020 33.4%,\n      #fff020 50.1%,\n      #3edf4b 50.1%,\n      #3edf4b 66.8%,\n      #3363ff 66.8%,\n      #3363ff 83.5%,\n      #b102b7 83.5%)",
        "sourceFile": "styles/presets/gradients.css"
      },
      {
        "title": "gradient multistripes",
        "slug": "gradient-multistripes",
        "variableName": "--gradient-multistripes",
        "value": "linear-gradient(219deg,\n      var(--color-1) 0%, var(--color-1) 19%, transparent 19%, transparent 20%,\n      var(--color-2) 20%, var(--color-2) 39%, transparent 39%, transparent 40%,\n      var(--color-3) 40%, var(--color-3) 59%, transparent 59%, transparent 60%,\n      var(--color-4) 60%, var(--color-4) 79%, transparent 79%, transparent 80%,\n      var(--color-5) 80%)",
        "sourceFile": "styles/presets/gradients.css"
      }
    ]
  },
  {
    "name": "presets-images",
    "label": "Images",
    "type": "variables",
    "view": "image",
    "tags": [],
    "items": [
      {
        "title": "image 2",
        "slug": "image-2",
        "variableName": "--image-2",
        "value": "url('https://images.pexels.com/photos/2382325/pexels-photo-2382325.jpeg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image leafs",
        "slug": "image-leafs",
        "variableName": "--image-leafs",
        "value": "url('/images/pexels-photo-2382325.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image color",
        "slug": "image-color",
        "variableName": "--image-color",
        "value": "url('/images/background-color.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image dots",
        "slug": "image-dots",
        "variableName": "--image-dots",
        "value": "url('/images/bernard-hermant-Jlh7u4NjNAQ-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image gradient",
        "slug": "image-gradient",
        "variableName": "--image-gradient",
        "value": "url('/images/gradienta-coj7UZ7iN60-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image dark",
        "slug": "image-dark",
        "variableName": "--image-dark",
        "value": "url('/images/kamran-abdullayev-LLS74TRAseM-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image colors",
        "slug": "image-colors",
        "variableName": "--image-colors",
        "value": "url('/images/li-zhang-K-DwbsTXliY-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image lights",
        "slug": "image-lights",
        "variableName": "--image-lights",
        "value": "url('/images/mahdi-bafande-DAA3aD4nKZc-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image reflect",
        "slug": "image-reflect",
        "variableName": "--image-reflect",
        "value": "url('/images/maxim-berg-ENIaPZytqzE-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image reflect2",
        "slug": "image-reflect2",
        "variableName": "--image-reflect2",
        "value": "url('/images/sean-sinclair-1xZ0SqLPE4E-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image reflect3",
        "slug": "image-reflect3",
        "variableName": "--image-reflect3",
        "value": "url('/images/sean-sinclair-cZgVpseeazg-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image reflect4",
        "slug": "image-reflect4",
        "variableName": "--image-reflect4",
        "value": "url('/images/sean-sinclair-gai1YB3UmDA-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image reflect5",
        "slug": "image-reflect5",
        "variableName": "--image-reflect5",
        "value": "url('/images/sean-sinclair-k0JNJRbrJAs-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image waves",
        "slug": "image-waves",
        "variableName": "--image-waves",
        "value": "url('/images/milad-fakurian-iFu2HILEng8-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image waves2",
        "slug": "image-waves2",
        "variableName": "--image-waves2",
        "value": "url('/images/milad-fakurian-nY14Fs8pxT8-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image waves3",
        "slug": "image-waves3",
        "variableName": "--image-waves3",
        "value": "url('/images/richard-horvath-_nWaeTF6qo0-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image waves4",
        "slug": "image-waves4",
        "variableName": "--image-waves4",
        "value": "url('/images/richard-horvath-is8jWT-mvng-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image waves5",
        "slug": "image-waves5",
        "variableName": "--image-waves5",
        "value": "url('/images/richard-horvath-RAZU_R66vUc-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image 3d",
        "slug": "image-3d",
        "variableName": "--image-3d",
        "value": "url('/images/milad-fakurian-PjG_SXDkpwQ-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image abstract",
        "slug": "image-abstract",
        "variableName": "--image-abstract",
        "value": "url('/images/orfeas-green-G5A5ZNjS2tE-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image abstract2",
        "slug": "image-abstract2",
        "variableName": "--image-abstract2",
        "value": "url('/images/pawel-czerwinski-prMn9KINLtI-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image abstract3",
        "slug": "image-abstract3",
        "variableName": "--image-abstract3",
        "value": "url('/images/valentin-beauvais-4YrVF0gVdjk-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image escene",
        "slug": "image-escene",
        "variableName": "--image-escene",
        "value": "url('/images/pramod-tiwari-Br0F5xMArxI-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image escene2",
        "slug": "image-escene2",
        "variableName": "--image-escene2",
        "value": "url('/images/pramod-tiwari-WHdC7jqTRlQ-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image fabric",
        "slug": "image-fabric",
        "variableName": "--image-fabric",
        "value": "url('/images/zac-ong-v2UYbS3EfXA-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      },
      {
        "title": "image dots",
        "slug": "image-dots",
        "variableName": "--image-dots",
        "value": "url('/images/bernard-hermant-Jlh7u4NjNAQ-unsplash.jpg')",
        "sourceFile": "styles/presets/images.css"
      }
    ]
  },
  {
    "name": "variables-color",
    "label": "Colors",
    "type": "variables",
    "view": "color",
    "tags": [],
    "items": [
      {
        "title": "color primary 50",
        "slug": "color-primary-50",
        "variableName": "--color-primary-50",
        "value": "oklch(0.95 0.03 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color primary 100",
        "slug": "color-primary-100",
        "variableName": "--color-primary-100",
        "value": "oklch(0.92 0.04 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color primary 200",
        "slug": "color-primary-200",
        "variableName": "--color-primary-200",
        "value": "oklch(0.88 0.06 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color primary 300",
        "slug": "color-primary-300",
        "variableName": "--color-primary-300",
        "value": "oklch(0.82 0.08 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color primary 400",
        "slug": "color-primary-400",
        "variableName": "--color-primary-400",
        "value": "oklch(0.75 0.10 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color primary 500",
        "slug": "color-primary-500",
        "variableName": "--color-primary-500",
        "value": "oklch(0.68 0.12 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "surface",
        "slug": "surface",
        "variableName": "--surface",
        "value": "oklch(0.98 0.01 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "card",
        "slug": "card",
        "variableName": "--card",
        "value": "oklch(0.98 0.01 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "text",
        "slug": "text",
        "variableName": "--text",
        "value": "oklch(0.25 0.03 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "accent",
        "slug": "accent",
        "variableName": "--accent",
        "value": "oklch(0.80 0.10 260)",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color 1",
        "slug": "color-1",
        "variableName": "--color-1",
        "value": "#186cb8",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color 2",
        "slug": "color-2",
        "variableName": "--color-2",
        "value": "#2a9a9f",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color 3",
        "slug": "color-3",
        "variableName": "--color-3",
        "value": "#f1b211",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color 4",
        "slug": "color-4",
        "variableName": "--color-4",
        "value": "#e83611",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "color 5",
        "slug": "color-5",
        "variableName": "--color-5",
        "value": "#f9002f",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "gold",
        "slug": "gold",
        "variableName": "--gold",
        "value": "#ffb338",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "light shadow",
        "slug": "light-shadow",
        "variableName": "--light-shadow",
        "value": "#77571d",
        "sourceFile": "styles/variables/colors.css"
      },
      {
        "title": "dark shadow",
        "slug": "dark-shadow",
        "variableName": "--dark-shadow",
        "value": "#3e2904",
        "sourceFile": "styles/variables/colors.css"
      }
    ]
  },
  {
    "name": "variables-font",
    "label": "Fonts",
    "type": "variables",
    "view": "font",
    "tags": [],
    "items": [
      {
        "title": "font sans",
        "slug": "font-sans",
        "variableName": "--font-sans",
        "value": "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Inter, Arial, Noto Sans, \"Apple Color Emoji\",\"Segoe UI Emoji\"",
        "sourceFile": "styles/variables/font.css"
      }
    ]
  }
];

export function getCategories(): Category[] {
  return CATEGORIES;
}

export function getCategory(name: string): Category | undefined {
  return CATEGORIES.find((c) => c.name === name);
}

export function getItem(category: string, itemSlug: string) {
  const cat = getCategory(category);
  return cat?.items.find((i) => i.slug === itemSlug);
}

export default CATEGORIES;
