import type { Metadata } from "next";
import localFont from "next/font/local";

import { Providers } from "@/components/providers"

import "./globals.css";

const geistSans = localFont({
  src: "../public/shared/fonts/GeistVF.woff",
  variable: "--font-sans",
});
const geistMono = localFont({
  src: "../public/shared/fonts/GeistMonoVF.woff",
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
