module.exports = {

    common: [
        'min-contrast',
        'max-contrast',
        'lightest',
        'darkest',
        'clear',
        'current',
    ],
    colors: [
        'primary',
        'secondary',
        'tertiary',
        'error',
        'success',
        'warning',
        'info',
    ],
    variants: [
        'DEFAULT',
        'hardest',
        'harder',
        'hard',
        'subtle',
        'subtler',
        'subtlest',
    ],
    accent: [
        'inactive',
        'active',
        'accent',
    ],
    background: [
        'background',
        'foreground',
        'surface',
        'surface-alpha',
        'surface-lower',
        'surface-low',
        'surface-medium',
        'surface-high',
        'surface-higher',
        'variant',
        'variant-dim',
        'variant-bright',
        'scrim',
        'scrim-hard',
        'scrim-soft',
    ],
    text: [
        'hardest',
        'default',
        'subtle',
        'muted',
        'disabled',
        'hint',
    ],
    icon: [
        'hardest',
        'default',
        'subtle',
        'muted',
        'disabled',
        'hint',
    ],
    form: [
        'filled',
        'disabled',
        'track',
    ],
    state: [
        'hover',
        'focus',
        'press',
        'drag',
    ],
    selection: [
        'DEFAULT',
    ],
    caret: [
        'DEFAULT',
    ],
    mark: [
        'DEFAULT',
        'highlight',
    ],
    divider: [
        'DEFAULT',
        'outline',
        'border',
        'line',
    ],
    border: [
        'DEFAULT',
        'outline',
        'divider',
        'line',

        'card',
        'popover',
        'dialog',
        'layout',
    ],
    outline: [
        'DEFAULT',
        'border',
        'divide',
        'line',
    ],
    ring: [
        'DEFAULT',
        'outline',
        'border',
        'divide',
        'line',
    ],
    shadow: [
        'DEFAULT',
        'hard',
        'base',
        'soft',
    ],
    layers: [
        'backward',
        'surface',
        'scrim',
        'content',
        'forward',

        'sticky',
        'fixed',
        'backdrop',
        'overlay',

        'lifted',
        'raised',
        'floating',
        'elevated',
        'suspended',
    ],
    chart: {
        categorical: [
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        ],
        sequential: [
            'from',
            'to',
        ],
        divergent: [
            'start',
            'middle',
            'end',
        ],
    },
    addons: {
        status: [
            'alert',
            'online',
            'offline',
        ],
        data: [
            'increment',
            'decrement',
        ],
        sentiment: [
            'negative',
            'intermediate',
            'positive',
            'neutral',
        ],
        commerce: [
            'new',
            'promo',
            'discount',
            'gift',
            'pay',
        ]
    },
    primitives: [
        'input',
        'button',
        'media',
        'list',
        'item',
        'card',
        'popover',
        'modal',
        'tool',
        'layout',
    ],
    primitive_addons: [
        'media',
        'audio',
        'video',
        'image',

        'thumbnail',
        'cover',
        'picture',
        'avatar',

        'input',
        'option',
        'field',

        'button',
        'control',
        'handler',
        'thumb',

        'menu',
        'tabs',
        'list',
        'grid',

        'item',
        'item-menu',
        'item-tab',
        'item-list',
        'item-grid',
        'item-row',
        'item-cell',

        'card',
        'dropdown',
        'popover',
        'dialog',
        'modal',
        'alert',

        'tool',
        'toolbar',
        'tooltip',

        'header',
        'footer',
        'sidebar',
        'content',

        'segment',
        'block',
        'section',

        'region',
        'layout',
    ],
    tints: [
        'active',
        'accent',
        'surface',

        'form',
        'text',
        'heading',
        'icon',
        'decoration',

        'highlight',
        'ambient',
        'variant',
        'scrim',
        'shadow',
        'states',
    ],
};