// @ts-nocheck -- skip type checking
import * as docs_8 from "../content/guides/writing-content.mdx?collection=docs&hash=1760367116277"
import * as docs_7 from "../content/guides/index.mdx?collection=docs&hash=1760367116277"
import * as docs_6 from "../content/guides/deployment.mdx?collection=docs&hash=1760367116277"
import * as docs_5 from "../content/guides/components.mdx?collection=docs&hash=1760367116277"
import * as docs_4 from "../content/getting-started/installation.mdx?collection=docs&hash=1760367116277"
import * as docs_3 from "../content/getting-started/index.mdx?collection=docs&hash=1760367116277"
import * as docs_2 from "../content/getting-started/configuration.mdx?collection=docs&hash=1760367116277"
import * as docs_1 from "../content/(root)/index.mdx?collection=docs&hash=1760367116277"
import * as docs_0 from "../content/(root)/about.mdx?collection=docs&hash=1760367116277"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"(root)/about.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/(root)/about.mdx"}, data: docs_0 }, { info: {"path":"(root)/index.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/(root)/index.mdx"}, data: docs_1 }, { info: {"path":"getting-started/configuration.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/getting-started/configuration.mdx"}, data: docs_2 }, { info: {"path":"getting-started/index.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/getting-started/index.mdx"}, data: docs_3 }, { info: {"path":"getting-started/installation.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/getting-started/installation.mdx"}, data: docs_4 }, { info: {"path":"guides/components.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/guides/components.mdx"}, data: docs_5 }, { info: {"path":"guides/deployment.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/guides/deployment.mdx"}, data: docs_6 }, { info: {"path":"guides/index.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/guides/index.mdx"}, data: docs_7 }, { info: {"path":"guides/writing-content.mdx","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/guides/writing-content.mdx"}, data: docs_8 }], [{"info":{"path":"meta.json","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/meta.json"},"data":{"pages":["(root)","getting-started","guides"],"root":true}}, {"info":{"path":"(root)/meta.json","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/(root)/meta.json"},"data":{"title":"Home","pages":["index","about"]}}, {"info":{"path":"getting-started/meta.json","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/getting-started/meta.json"},"data":{"title":"Getting Started","pages":["index","installation","configuration"]}}, {"info":{"path":"guides/meta.json","absolutePath":"/Users/cristian/Sites/volta.wtf/templates/sitedocs/content/guides/meta.json"},"data":{"title":"Guides","pages":["index","writing-content","components","deployment"]}}])